### ISSUE TITLE
Ошибка при изменение количества товаров в корзине

### ISSUE THREAD

**Issue by vasilev-alex** [modx-pro/miniShop2#108]
При изменение количества товара в корзине, товар удалялся из таблицы товаров (но не из корзины). Количество изменялось и при обновлении страницы товар снова появлялся в таблице товаров (в корзине). Выяснил, что в default.js идет проверка на key из data, который приходит с сервера и содержит 'total_count',  'total_cost', 'total_weight' но в нем нет того самого key. После добавление все заработало нормально. 

Добавление в mscarthandler.class.php
Метод  public function status($data = array())

**Comment by bezumkin** [comment]
На тестовом сайте с последней версией ошибки нет http://minishop2.com/

**Comment by webinmd** [comment]
В последней версии компонента данная ошибка не воспроизводится
