### ISSUE TITLE
Если фокус был на поле - то не происходит отправка заказа

### ISSUE THREAD

**Issue by adminoid** [modx-pro/miniShop2#123]
По файлу /assets/components/minishop2/js/web/default.js
В общем, onchange затирает onsubmit и если фокус стоял на редактировании последнего поля, а потом кликнули по кнопке - отправить - отправки не происходит.

Вот как я это пофиксил, на скорую руку:

Где вешаются события:

miniShop2.$doc
                    .on('mousedown', 'button[value="order/submit"]', function(e) {
                        miniShop2.submitting = true;
                    })

Где идет onchange:

if(miniShop2.submitting){
                            return true;
                        }

Где отправка заказа:

,submit: function() {

```
        miniShop2.submitting = false;
```

...
}

**Comment by Ibochkarev** [comment]
Не воспроизводится
