### ISSUE TITLE
Не удаляются записи из таблицы modx_ms2_products 

### ISSUE THREAD

**Issue by Bournwog** [modx-pro/miniShop2#124]
Не удаляются записи из таблицы modx_ms2_products при удалении товаров, происходит это рандомно, так же записи в таблице изображений не удаляются, хотя сами изображения удаляются. Как вариант предусмотреть принудительный процессор для очистки таблиц с отмершими записями.

**Comment by bezumkin** [comment]
<blockquote>Не удаляются записи из таблицы modx_ms2_products при удалении товаров, происходит это рандомно</blockquote>

Если и так (чего никто не замечал), то вопросы нужно задавать в xPDO, ибо этим удалением занимается он.

В [схеме](https://github.com/bezumkin/miniShop2/blob/master/core/components/minishop2/model/schema/minishop2.mysql.schema.xml) всё прописано как надо, вручную ничего не удаляется - только через связи:

``` xml
<composite alias="Data" class="msProductData" local="id" foreign="id" cardinality="one" owner="local" />
```

<blockquote>так же записи в таблице изображений не удаляются, хотя сами изображения удаляются</blockquote>

Ну тогда нужно смотреть логи своего MySQL сервера. Уж битые картинки на страницах товаров точно кто-нибудь заметил бы и раньше.

Думаю, что проблема локальна. Ради интереса можно проверить работу на  http://test.modx.pro

**Comment by Bournwog** [comment]
не проблема не в битых картинках, а в том что удаляя ресурс он удаляется из таблицы site_content но не удаляется из таблицы ms2_products, записи картинок тоже не удалились, конечно можно выполнить 1 запрос для очистки, но просто странно немного видеть такой вариант развития событий

**Comment by Bournwog** [comment]
А что будет если человек создал заказ, а после товары были удалены с сайта, какая информация останется в таблицах?

**Comment by bezumkin** [comment]
Останется id удалённого товара.
