### ISSUE TITLE
При загрузке картинок в галерею остаются файлы в корне

### ISSUE THREAD

**Issue by argnist** [modx-pro/miniShop2#125]
https://github.com/bezumkin/miniShop2/blob/a0d8f198a7b3bb5cac4b6abfd654c75d1bac5d0f/core/components/minishop2/model/minishop2/msproductfile.class.php#L112

Вот здесь, если phpThumb не может сделать превьюшки, получается, что файлы не удаляются.

Почему превьюшки не получаются тоже вопрос. getimagesize() от загружаемого файла ничего не возвращает, хотя файл открывается разными просмотрщиками, в том числе из браузера, если его загрузить по фтп.

**Comment by bezumkin** [comment]
Как обычно - проверяем работу на http://test.modx.pro и разбираемся со своим хостингом.

Невозможность обработать картинку - нештатная ситуация.

**Comment by argnist** [comment]
Ага, с phpThumb помогла установка Imagick http://bezumkin.ru/sections/php/619/
Ну файлы все равно должны чиститься, даже если ошибка - unlink пониже перенести.

**Comment by bezumkin** [comment]
Перенеси, предложи pull request. Так и работает open source.

**Comment by Ibochkarev** [comment]
~~Fixed in https://github.com/argnist/miniShop2/commit/2319857550671a68715407832f8179270146e0a2~~

**Comment by Ibochkarev** [comment]
@vgrish можно и нужно ли добавить https://github.com/argnist/miniShop2/commit/2319857550671a68715407832f8179270146e0a2

**Comment by Ibochkarev** [comment]
Исправлено в #349
