### ISSUE TITLE
Потеря русских символов

### ISSUE THREAD

**Issue by Ser1ous** [modx-pro/miniShop2#136]
При такой строке в csv.php 

``` php
while (($csv = fgetcsv($handle, 0, $delimeter)) !== false) {
```

Иногда теряются русские символы, от чего это точно зависит я не помню. Но раньше сталкивался, и сейчас столкнулся.
Предлагаю эту конструкцию, заменить на это 

``` php
while ($contents_csv = fgets($handle)){
$csv = explode($delimeter, $contents_csv);
```

Принцип тот же самый, но.
1) Русские символы не теряются.
2) Скорость выполнения выше. Тестировал на 16 000 строк.  Проигрыш примерно 10 раз в скорость у fgetcsv, но если до 2 000 строк, то время выполнения примерно одинаковое.

**Comment by grachov** [comment]
Значения в CSV могут быть заэкранированы и заключены в кавычки (если содержат недопустимые символы, например, пробелы). С обычным `explode` это все будет проигнорировано.

**Comment by Ser1ous** [comment]
Ну да в этой ситуации, очевидно выигрывает fgetcsv.

Но не так много людей использует "some text" такой принцип для того чтобы задать текст.

И я до сих пор не понял, почему пропадает русский текст при fgetcsv. Для русскоязычного сайта отказ от русского языка в описании, сложнее пережить, чем не использование для разбивки символы типа пробел и запятая и точка. А по старинке использовать точку с запятой, как это автоматом делает google docs и excel.

**Comment by grachov** [comment]
Если в одном из полей строки встретится `$delimeter`, то получится неправильное количество колонок при использовании `explode`, вот в чем главная проблема.

Русский текст скорее всего пропадает из-за проблем с кодировкой файла.

**Comment by Ser1ous** [comment]
Сюда я не писал. Проверял с кодировками UTF-8(c) без BOM, WIN-1251, KOI8-R(ну малоли). На двух разных серверах было, и я не знаю какой сервер. А с explode отлично работает.
Вообще это сложный вопрос что из двух вариантов лучше. Т.к. мало кто оборачивает текст в кавычки.
