### ISSUE TITLE
item added to cart but cart shows empty in firefox if user is not logged in

### ISSUE THREAD

**Issue by nick2687** [modx-pro/miniShop2#138]
for this site: https://sandramillerfloral.com

when adding an item to the cart, the cart will update with the new item, if you refresh the page the cart shows as being empty. if you then add another item the cart will update to show 2 items, but again show as empty if you refresh the page.

This only seems to happen in firefox and safari

The session does not seem to be getting carried across.

**Comment by argnist** [comment]
Have you fixed this?

**Comment by nick2687** [comment]
Yes this was resolved, forgot I opened this issue. It ended up being a caching issue on the server. 

Thanks.
