### ISSUE TITLE
Сортировка товаров в категории

### ISSUE THREAD

**Issue by webkostya** [modx-pro/miniShop2#140]
Установил miniShop2 версии 2.1.7 на чистый MODx. Если отсортировать товар по убыванию/возрастанию то потом перетаскивая товар методом Drag&Drop визуально не видно перемещение товара, но на сайте все отображается правильно, то есть все работает, просто визуально этого не видно. Было замечено, что если выскочил такой глюк в одном браузере то в другом его не будет (пока не отсортируешь).

Вот чистый MODx с одним лишь miniShop2 (2.1.7 pl2):
http://extra.homchenkokostya.modxcloud.com/manager/
Login: admin
Password: 123123

**Comment by argnist** [comment]
Это не баг. Сортировка перетаскиванием меняет поле menuindex у товара. По умолчанию его нет, но можно добавить в настройке ms2_category_grid_fields и отсортировать уже по этому полю в админке. А сортировка по убиванию/возрастанию работает только для админки, чтобы можно было найти определенные товары.
