### ISSUE TITLE
Support ContentBlocks 

### ISSUE THREAD

**Issue by Mark-H** [modx-pro/miniShop2#159]
I've got a request for minishop2 to support contentblocks and figured I'd open an issue here. It'll likely be a one-line change in the minishop code per our documentation: https://www.modmore.com/extras/contentblocks/documentation/custom-resources/#jump_implementing_contentblocks_support

I've not done any work with miniShop myself yet, so don't have an immediate test site to send a PR unfortunately. :(

**Comment by jGleitz** [comment]
I have created a pull request for this: https://github.com/bezumkin/miniShop2/pull/160

I think it would make sense to add an options to minishop2 to show the content-field of a Product in full width below everything in an own box, like it is done for normal modx-resources. ContentBlocks would look much nicer then.

**Comment by Ibochkarev** [comment]
Related #160
