### ISSUE TITLE
Product Resource TVs gone when MODx Option "tvs_below_content" selected

### ISSUE THREAD

**Issue by domindian** [modx-pro/miniShop2#162]
When the Modx sytem option "tvs_below_content" is selected, Minishop doesn't show them. 
Can anyone think of a quick fix?

regards, d~

**Comment by ghost** [comment]
+1

При настройке в core tvs_below_content=Да не показывает дополнительные поля созданные через TV

**Comment by SoftAlex** [comment]
+1

**Comment by argnist** [comment]
Повтор https://github.com/bezumkin/miniShop2/issues/150 , решено в 2.2.0-beta
