### ISSUE TITLE
syncsite missing as default field in: ms2_product_main_fields

### ISSUE THREAD

**Issue by markwillis82** [modx-pro/miniShop2#171]
If using the "auto publish/unpublish" feature within MODX, this setting needs to be checked to force the auto_publish cache key to be updated with the new dates otherwise the product never gets published.

By adding syncsite to the main fields of the product this issue is fixed.

Was there a reason to remove it in the first place?

**Comment by argnist** [comment]
Проверил. Почему-то, если не выводить в ms2_product_main_fields параметр syncsite, запланированные задания на публикацию не выполняются. Легче всего просто добавить этот параметр по умолчанию...
