### ISSUE TITLE
Получение параметров при мультидоменности

### ISSUE THREAD

**Issue by Setest** [modx-pro/miniShop2#176]
Если использовать несколько сайтов на одном ядре, и разделять отображение доп параметров (плагины) в админке, то мы всегда получаем параметры из системных параметров, а не из контекстов.  Конечно данную фишку пока нельзя будет отразить в заказах так как там нет переключения контекстов, но можно например добавить в  /core/components/minishop2/controllers/product/update.class.php
перед

``` javascript
if (!$product_extra_fields = $this->modx->getOption('ms2_product_extra_fields')) {
            $product_extra_fields = 'article,price,old_price,weight,color,remains,reserved,vendor,made_in,tags';
        }
```

переключение контекста с mgr, с целью правильно получить опции.

**Comment by vgrish** [comment]
https://github.com/bezumkin/miniShop2/pull/340
