### ISSUE TITLE
Формат цен: лишние нули

### ISSUE THREAD

**Issue by Rachind** [modx-pro/miniShop2#177]
В настройках minishop2 есть пункт «Формат цен» и «Убирать лишние нули в ценах». Если формат цен такой [2, ".", " "], т.е. разделитель точка, то лишние нули отбрасываются хорошо. Если формат [2, ",", " "], с разделителем запятая, то отбрасывание лишних нулей не работает и цены отображаются так 2 753,00. Не могу понять, баг ли это или я что-то недопонял.

**Comment by grachov** [comment]
Похоже на баг, потому что в коде идет [жесткая привязка](https://github.com/bezumkin/miniShop2/blob/master/core/components/minishop2/model/minishop2/minishop2.class.php#L479-L480) к разделителю-точке.

**Comment by argnist** [comment]
Повтор #175
