### ISSUE TITLE
Пересчет стоимости заказа в админке

### ISSUE THREAD

**Issue by AsymptotaX** [modx-pro/miniShop2#178]
В админке, во вкладке "Покупки" заказа, при добавлении вручную товара, сумма заказа не пересчитывается.  Однако, он пересчитывается, если снова зайти в "Покупки", и отредактировать любой товар.

**Comment by grachov** [comment]
Проблема в том, что в [create процессоре](https://github.com/bezumkin/miniShop2/blob/master/core/components/minishop2/processors/mgr/orders/product/create.class.php) не хватает метода `afterSave` (по аналогии с [remove](https://github.com/bezumkin/miniShop2/blob/master/core/components/minishop2/processors/mgr/orders/product/remove.class.php#L30) и [update](https://github.com/bezumkin/miniShop2/blob/master/core/components/minishop2/processors/mgr/orders/product/update.class.php#L56)):

``` php
public function afterSave() {
  $this->order->updateProducts();
}
```

**Comment by AsymptotaX** [comment]
Да, спасибо. Уже добавил, все заработало.

**Comment by vgrish** [comment]
https://github.com/bezumkin/miniShop2/pull/335
