### ISSUE TITLE
JS изменение visibility на empty/not_empty в Msminicart

### ISSUE THREAD

**Issue by salacoste** [modx-pro/miniShop2#179]
Описано подробно тут https://modx.pro/help/5649/

При дублирующей верстке мини корзины, когда контент в элементах с классами empty/not_empty повторяется, требуется изменять visibility этих элементов при первом добавлении товара в пустую корзину.

**Comment by argnist** [comment]
У вас верстка неправильная. Зачем это дублирование с empty/notempty когда есть класс full, который выставляется в том числе в js. А все остальное настраивается в CSS исходя из этого класса.
