### ISSUE TITLE
Не хватает записей лексикона в опциях, 2.2.0-beta3

### ISSUE THREAD

**Issue by Shiriaev** [modx-pro/miniShop2#181]
В разделе настройки --> опции, при добавлении новой опции, выпадающий список «тип свойства», не хватает записей лексиконов:

ms2_ft_checkbox
ms2_ft_combo-options

**Comment by argnist** [comment]
Они есть, вы кеш не почистили после обновления скорее всего.

**Comment by Shiriaev** [comment]
Вычистил все кэши — все по прежнему. Дело в том, что  ms2_ft_checkbox
и ms2_ft_combo-options — таких ключей просто нет ни в одном ru лексиконе ms2. Обновлялся с beta2.
Собственно, в указанном выпадающем списке вместо названий как раз вот эти ключи:

Полный список такой:

ms2_ft_checkbox
Да/Нет
Выпадающий список
Множественный список
ms2_ft_combo-options
Дата
Числовое поле
Текстовая область
Текстовое поле

**Comment by Shiriaev** [comment]
Удалил beta3 полностью, затем почистил кэш, установил ее же заново — ключи подтянулись, стало все ОК.
