### ISSUE TITLE
SEO оптимизация для pdoPage

### ISSUE THREAD

**Issue by salacoste** [modx-pro/miniShop2#189]
Для оптимального индексирования постраничной разбивки товаров (например) магазина необходимо включить для page>1 мета тег

```
<meta name="robots" content="noindex, follow">
```

Предлагаю дополнить условие

```
if (!empty($setMeta) && !$isAjax) {
            if ($page > 1) {
                $modx->regClientStartupHTMLBlock('<link rel="prev" href="' . $pdoPage->makePageLink($url, $page - 1) . '"/>');
                $modx->regClientStartupHTMLBlock('<meta name="robots" content="noindex, follow"/>');
            }
            if ($page < $pageCount) {
                $modx->regClientStartupHTMLBlock('<link rel="next" href="' . $pdoPage->makePageLink($url, $page + 1) . '"/>');
            }
        }


```

**Comment by bezumkin** [comment]
Есть прямо таки 100% уверенность, что этот мета-тег должен обязательно быть, работать, и никакого вреда от него не будет?

Я в этих SEO делах не понимаю, поэтому у меня такой уверенности нет. Предлагаю почитать [обсуждение на схожую тему](https://modx.pro/components/5173-pdotools-meta-tags-and-snippets-pdotitle/#comment-37042). **noindex** - это, выходит, не индексировать товары на страницах > 1?

Пока что можно прописать в шаблоне что-то такое, использую pdoParser:

```
[[!#get.page:isnot=``:then=`<meta name="robots" content="noindex, follow"/>`]]
```

**Comment by salacoste** [comment]
В моем случае все работает так, как должно, я добавил код.
Я изучил эту тему, потом раскинул сам, спросил на maultalk у подрядчика, который оптимизирует наши проекты. Именно он предложил добавлять такой тег на вторые и последующие страницы пагинации.

Проблема в данном случае в том, что при индексации 2й и последующих страниц 80+% контента на странице будет идентичным, отличаться будут только название товаров (статей) и тайтл (на пару символов, если добавлять стр. n).
По этой причине у поисковика будет 5-10 страниц с одинаковым контентом и тогда это негативно скажется на "главную" страницу категории (page 1), так как ее релевантность и уникальность упадет.
Noindex закроет от индексации все страницы кроме первой, что повысит ее уникальность, а follow позволит роботу ходить по ссылкам на товары/статьи, которые выдаются на второй и следующий страницах и индексировать сами товары без потерь.

Предлагаю эту опцию оставить на откуп пользователей, просто добавить setMeta = 2, тогда будет  добавляться и prev;next и noindex,follow.
