### ISSUE TITLE
Adding attributes to a product

### ISSUE THREAD

**Issue by m-altmeyer** [modx-pro/miniShop2#191]
First I would like to thank the author of this Plugin for his work, I really appreciate the simple shop system!

Now my issue: Is there any way to add more attributes than the default ones to a product? I need an additional attribute besides color and size and was not able to figure out how to do this?

Thank you very much!

**Comment by govza** [comment]
Unfortunately [Documentation](http://docs.modx.pro/components/minishop2/interface/the-characteristics-of-the-goods#Заполнение-новых-характеристик-товаров) only in russian, but you can googletranslate

**Comment by m-altmeyer** [comment]
Thank you very much for the reply, I'll try to understand the Documenation by using Google translate as you suggested.

**Comment by m-altmeyer** [comment]
Hello again,
I saw in your link that this feature is available only for versions 2.2+. However the latest version on the modX Package Browser is 2.1.12-pl? When I click "Search for Updates" modX tells me that this is the latest version. How can I update my version to 2.2?

Thank you very much and merry christmas!

**Comment by bezumkin** [comment]
Uploaded version 2.20-pl2 to modx.com, you can update.

**Comment by m-altmeyer** [comment]
Thank you so much! It just appeared in the package browser! That was fast!

All the best,
Max
