### ISSUE TITLE
Иконки товаров и категории

### ISSUE THREAD

**Issue by t3mnikov** [modx-pro/miniShop2#197]
Добрый день, Василий!
Добавьте в системные настройки minishop2 параметры: 
mgr_tree_icon_msproduct = "icon-gift"
mgr_tree_icon_mscategory = "icon-shopping-cart"

**Comment by iWatchYouFromAfar** [comment]
Иконки к товарам и категориям задаются в шаблонах. Для категорий можно использовать системную настройку **mgr_tree_icon_mscategory**, которая задаст иконку для всех категорий (если в шаблоне не прописана иконка).
