### ISSUE TITLE
Не выводятся товары, если превью формата 0x300

### ISSUE THREAD

**Issue by udovichenko** [modx-pro/miniShop2#199]
Видимо, проблема с нулем в начале.
Превьюшки генерируются, но не выводятся через
`[[msProducts?
    &includeThumbs=`0x300`
]]`

showLog выдает:
`Could not leftJoin msProductFile as 0x300`
`Added selection of msProduct: '0x300'.'url' as '0x300'`
`Could not process query, error #1054: Unknown column '0x300.url' in 'field list'`

Если наоборот превью размером 300x0, то все в порядке.

Проверял на
miniShop 2.2.0-pl2
MODX 2.3.4-pl

**Comment by bezumkin** [comment]
Должно быть `x300`
