### ISSUE TITLE
Некорректная работа опции "Убирать лишние нули" при формате цен [0, ".", " "]

### ISSUE THREAD

**Issue by inogo** [modx-pro/miniShop2#204]
Не совсем баг, скорее недочет. Если в качестве формата цены указать [0, ".", " "] (т. е. округлять до рубля) при активной опции "Убирать лишние нули в ценах", то в корзине нули отсекаются от целой части числа. Например, сумма 4900 форматируется в "4 9", вместо ожидаемого "4 900".

Причина ошибки в файле /assets/components/minishop2/js/web/default.js, а именно в функции [miniShop2.Utils.formatPrice](https://github.com/bezumkin/miniShop2/blob/master/assets/components/minishop2/js/web/default.js#L486-L495).

На этом участке кода:

``` javascript
if (miniShop2Config.price_format_no_zeros) {
    price = price.replace(/(0+)$/, '');
    price = price.replace(/[^0-9]$/, '');
}
```

Можно добавить проверку:

``` javascript
if (pf[0] > 0 && miniShop2Config.price_format_no_zeros) {
    price = price.replace(/(0+)$/, '');
    price = price.replace(/[^0-9]$/, '');
}
```

**Comment by bezumkin** [comment]
Просьба проверить наличие бага в версии 2.4+

**Comment by Ibochkarev** [comment]
@inogo актуально?

**Comment by webinmd** [comment]
для версии 2.4.18 не актуально

**Comment by Ibochkarev** [comment]
Исправлено ранее

**Comment by vgrish** [comment]
очень даже актуально

**Comment by Ibochkarev** [comment]
Fixed #336
