### ISSUE TITLE
модуль оплаты PayPal функционирует не корректно

### ISSUE THREAD

**Issue by iw96** [modx-pro/miniShop2#210]
После осуществления оплаты с помощью PayPal, в личном аккаунте PayPal не отображаются детали платежа: название, количество и стоимость каждого товара. Есть только общая информация и общая сумма (хотя перед осуществлением платежа, при переходе на страницу оплаты PayPal, список товаров есть). Такую же ситуацию описывают ребята здесь (только там движок osCommerce): http://forums.oscommerce.com/topic/382346-items-not-included-in-paypal-transaction-details-simply-the-url-of-the-store/
В этой же ветке на форуме запостили ответ от службы поддержки PayPal, где они отвечают:

> osCommerce is missing a crucial piece in the PayPal Express Checkout integration if you want this information to be displayed in the transaction details.
> Whether or not this is intended, is perhaps a feature you still need to enable or whether osCommerce just doesn't support it yet is a question for the osCommerce developer.

Ниже скриншот выписки платежа, где видно только общую информацию, но список товаров не отображается.

![screenshot from 2016-05-04 15-49-58](https://cloud.githubusercontent.com/assets/19189092/15017569/b99f904e-121e-11e6-81a7-8a345eee9b8c.png)

**Comment by iw96** [comment]
Разобрался с проблемой. Чтобы список товаров отображался в письме-уведомлении от пайпал и в информации о транзакции, нужно добавить в массив список товаров при вызове метода DoExpressCheckoutPayment (так как это сделано при вызове метода SetExpressCheckout). Добавил это после строки 86 в paypal.class.php:

```
            /* @var msOrderProduct $item */
            $i = 0;
            if ($order->get('status') > 1) {
                return $this->error('ms2_err_status_wrong');
            }
            $products = $order->getMany('Products');
            foreach ($products as $item) {
                /* @var msProduct $product */
                $name = $item->get('name');
                if (empty($name) && $product = $item->getOne('Product')) {
                    $name = $product->get('pagetitle');
                }
                $params['L_PAYMENTREQUEST_0_NAME'.$i] = $name;
                $params['L_PAYMENTREQUEST_0_AMT'.$i] = str_replace(',', '.', $item->get('price'));
                $params['L_PAYMENTREQUEST_0_QTY'.$i] = $item->get('count');
                $i++;
            }
```

К сожалению, не разобрался еще как запостить pull-request, поэтому отвечаю здесь...

**Comment by Ibochkarev** [comment]
Fixed #387
