### ISSUE TITLE
Не экранируются двойные кавычки в опциях

### ISSUE THREAD

**Issue by t3mnikov** [modx-pro/miniShop2#211]
При добавлении опции с " кавычками - текст опции не отображается.

![test](https://cloud.githubusercontent.com/assets/11781965/15282938/62b4d750-1b4f-11e6-8a89-599a72ee48ec.jpg)
![test2](https://cloud.githubusercontent.com/assets/11781965/15282939/62b6925c-1b4f-11e6-83f3-0f2694fdbc9f.jpg)

**Comment by bezumkin** [comment]
Если я правильно понял ошибку, то исправлено в 2.4.0 - просьба проверить.

**Comment by t3mnikov** [comment]
Здравствуйте, Василий!
Проверил, ошибка исправлена. Всё отлично!
![test_option](https://cloud.githubusercontent.com/assets/11781965/18503373/5397d0ea-7a65-11e6-8bb6-2a8282a40f29.jpg)
