### ISSUE TITLE
Не работает поиск в категории по числовым значениям

### ISSUE THREAD

**Issue by Trrad07** [modx-pro/miniShop2#213]
Если ввести число в поле поиск внутри категории, ничего не находит. По словам ищет.  
![search1](https://cloud.githubusercontent.com/assets/6637573/15698521/586ee458-27e7-11e6-9ba4-a52d0c775753.jpg)

![search2](https://cloud.githubusercontent.com/assets/6637573/15698526/6054a522-27e7-11e6-8912-81432e512168.jpg)

![search3](https://cloud.githubusercontent.com/assets/6637573/15698529/64e4cd24-27e7-11e6-9a96-4c2c97e695a8.jpg)

**Comment by bezumkin** [comment]
Исправлено https://github.com/bezumkin/miniShop2/commit/4c0dcc4534b398e19d2c4ee635269af0fe942588#diff-f24a9f71ae7fdc51956fe2999f013f15R53
