### ISSUE TITLE
Стиль основной картинки товара. mgr  

### ISSUE THREAD

**Issue by Trrad07** [modx-pro/miniShop2#214]
В стиле редактирования товара.
[https://github.com/bezumkin/miniShop2/blob/master/assets/components/minishop2/css/mgr/main.css#L141](https://github.com/bezumkin/miniShop2/blob/master/assets/components/minishop2/css/mgr/main.css#L141)  поменять/добавить  `#minishop2-product-image { max-width: 100%;height: auto; }`

**Comment by Ibochkarev** [comment]
Исправлено ранее: https://github.com/bezumkin/miniShop2/blob/master/assets/components/minishop2/css/mgr/main.css#L150
