### ISSUE TITLE
Не загружаются картинки в формате svg в дефолный медиа источник магазина

### ISSUE THREAD

**Issue by Semdevmaster** [modx-pro/miniShop2#232]
После обновления miniShop2 до последней версии возникли проблемы с загрузкой картинок в формате svg, раньше достаточно было добавить расширение в источник файлов MS2 Images и всё отлично работало, но теперь ни в какую не пропускает svg — пишет Файл не является корректным изображением.
Данная проблема присутствует и при абсолютно чистой установке miniShop2 на хостинге modhost.pro
Либо я всё-таки что то не так делаю либо это реально проблема в обновлении.
![bug](https://cloud.githubusercontent.com/assets/2706508/18238796/2fe51f4a-7349-11e6-8342-006c1cc39bb1.png)

**Comment by bezumkin** [comment]
Либо svg не является растровым изображением, из которого можно сгенерировать превью через phpThumb.

Попробуйте убрать его из изображений, и добавить в разрешенные типы файлов.

**Comment by bezumkin** [comment]
Ответа нет, будем считать, что вопрос снят.
