### ISSUE TITLE
Цепочка событий двух плагинов на изменение цены товара

### ISSUE THREAD

**Issue by romanlex** [modx-pro/miniShop2#235]
Требуется разъяснения по поводу невозможности получить новую цену при добавлении в корзину. Относится вопрос непоcредственно к работе minishop2.
Имеем: minishop2, cityFields, msOptionsPrice2
**cityFields** используется для разделения цен по городам. Висит на событии _msOnGetProductPrice_ что вроде как логично
**msOptionsPrice2** - используется для изменения цен с опциями товаров.

Цепочка событий следующая:
- Загружаем страницу товара
- Получаем актуальную для города цену по событию _msOnGetProductPrice_
- Меняем опцию товара(к примеру размер). 
- Добавляем товар в корзину с новой ценой
- Цена увеличивается в компоненте **msOptionsPrice2** по событию _msOnBeforeAddToCart_ которое в свою очередь вызывает метод getPrice() у товара
- возвращаемся в метод **add** в классе **msCartHandler**

``` php
            $response = $this->ms2->invokeEvent('msOnBeforeAddToCart', array(
                'product' => $product,
                'count' => $count,
                'options' => $options,
                'comment' => $comment,
                'cart' => $this,
            ));

            if (!($response['success'])) {
                return $this->error($response['message']);
            }

            $price = $product->getPrice();
            $weight = $product->getWeight();
            $count = $response['data']['count'];
            $options = $response['data']['options'];
            $comment = $response['data']['comment'];
```
- видим что цена при добавлении в корзину снова переопределяется в методе **$product->getPrice();**, который в свою очередь вызывает событие _msOnGetProductPrice_, а на этом событии висит **cityFields**, который снова определяет цену согласно городу и устанавливает её.

Получается цена в итоге, которая была переопределена событием _msOnBeforeAddToCart_, переопределяется менее значимым _msOnGetProductPrice_
Причем логика в принципе других компонентов корректна.

**Comment by bezumkin** [comment]
Что мешает автору этих дополнений определять цену товара в одном единственном событии, которое именно для этого и предназначено - **msOnGetProductPrice**?
