### ISSUE TITLE
Добавить event на создание пользователя, при оформлении заказа

### ISSUE THREAD

**Issue by but1head** [modx-pro/miniShop2#243]
Не хватает уведомления "вы зарегистрированы на сайте... ваш логин и пароль:".
Было бы очень хорошо добавить эвент msOnCreateUser, внутри 
public function getCustomerId() например.

**Comment by bezumkin** [comment]
Можно же на стандартном событии **OnUserSave** указать новому пользователю любой пароль и отправить письмо на почту. Еще одно событие для этого не нужно.
