### ISSUE TITLE
Небольшой баг с редактированием поля "Производитель" из категории товаров

### ISSUE THREAD

**Issue by vladmirx** [modx-pro/miniShop2#244]
Если в настройках Minishop2 в grid категории товаров добавлено поле vendor и попытаться его обновить из категории товаров, то при двойном щелчке подставится не текущий производитель, а первый, т.к. в запросе получения категорий пустой id:
- action: mgr/settings/vendor/getlist
- id:

![firefox_2016-09-28_18-11-27](https://cloud.githubusercontent.com/assets/22282805/18911861/7335f1d0-85a9-11e6-8b2d-a78c8ae6700c.png)

**Comment by vgrish** [comment]
https://github.com/bezumkin/miniShop2/pull/337
