### ISSUE TITLE
msProduct не выводит одно значение опции

### ISSUE THREAD

**Issue by Electrica** [modx-pro/miniShop2#245]
При вызове msProduct, если указано только одно значение, не выводит, пустой массив, если указать два и более все нормально отрабатывается.

**Comment by Ibochkarev** [comment]
Исправлено в:
https://github.com/bezumkin/miniShop2/commit/05f6092f0b5d7f576c379f7624959a5a48117889
https://github.com/bezumkin/miniShop2/commit/05f6092f0b5d7f576c379f7624959a5a48117889
