### ISSUE TITLE
Превью картинки

### ISSUE THREAD

**Issue by Electrica** [modx-pro/miniShop2#246]
Не показывает превью картинки в галерее miniShop2. Во вкладке товар показывает нормально[http://clip2net.com/s/3CKjczX](url)

**Comment by bezumkin** [comment]
Ну это из-за чего угодно может быть и точно не ошибка компонента.

На демо-сайте всё показывает. <img width="1049" alt="2016-09-29 17 53 15" src="https://cloud.githubusercontent.com/assets/1257284/18951141/a6be7760-866d-11e6-987e-6e235088ee06.png">

**Comment by Electrica** [comment]
Ок, буду смотреть, что не так. Спасибо!
