### ISSUE TITLE
Проблема при сортировке изображений с thumbnails

### ISSUE THREAD

**Issue by morfin60** [modx-pro/miniShop2#249]
В процессе тестирования заметил проблему при сортировке изображений - 
1. Настраиваю генерацию thumbnails 120x70 и 360x510 для изображений
2. Загружаю 1.jpg и 2.jpg(у них соответственно rank 0 и 1, также и у thumbnails)
3. Меняю их местами и получаю 6 записей с rank 1 1 1(это 1.jpg) и 0 1 1(у 2.jpg)
В коде сниппета делается leftJoin следующим образом:
`$leftJoin[$thumb] = array(
            'class' => 'msProductFile',
            'on' => "`{$thumb}`.product_id = msProduct.id AND `{$thumb}`.rank = 0 AND `{$thumb}`.path LIKE '%/{$thumb}/%'",
        );`
Это вызывает проблемы при выборке изображения, которое будет отображаться в списке продуктов. Также при удалении изображения с rank 0 не выбирается изображение. Предполагаемый фикс - делать выборку изображения с минимальным ранком и делать апдейт для дочерних thumbnails

**Comment by Ibochkarev** [comment]
Проблема не воспроизводится
