### ISSUE TITLE
Вывод опции например 0.0

### ISSUE THREAD

**Issue by Electrica** [modx-pro/miniShop2#251]
Если опция выглядит вот так: 
- 0.00
- 0.25
  и так далее, у меня так в виде оптической силы линз, то он не выводит ее, если она одна.
  Бага на этой строчке https://github.com/bezumkin/miniShop2/blob/master/core/components/minishop2/elements/snippets/snippet.ms_options.php#L23
  Если убрать проверку, то все отлично.
  `if (!empty($name) && $option = $product->get($name)) {
      $options[$name] = $option;
  }`

**Comment by Pathologic** [comment]
Лучше тогда не убирать проверку, а поменять на "if ($option[0] !== '') {"

**Comment by CrazyBoy49z** [comment]
Вывод сделать в формате 0.0 не получится без костилей, так как проблема в PHP. Можно переделать проверку и выводить 0, что в большом случае не нужно. 

Решение использовать 0.01 или ещё меньше 0.0001.

**Comment by CrazyBoy49z** [comment]
Проверил на рабочем проекте так как сайт тоже специализируется на оптических линзах. Только там всё заполнено через запятую проблем не возникло. 

Указал диоптрию 0,00 на сайте всё работает без изменения кода. Потому принимаю решение, что не нужно костылей лепить.

![image](https://user-images.githubusercontent.com/3448603/87831128-457c3a00-c88b-11ea-8ef8-ac76602cc4c7.png)
![image](https://user-images.githubusercontent.com/3448603/87831161-57f67380-c88b-11ea-95f9-3b3dad664dfa.png)
