### ISSUE TITLE
Вырезает чешские символы в имени пользователя в заказе.

### ISSUE THREAD

**Issue by kolengri** [modx-pro/miniShop2#253]
Приветствую! 
При создании заказа с именем, к примеру, Jakub Kovář полностью порежет все чешские символы. Останется Jakub Kov

![screen shot 2016-10-18 at 21 19 56](https://cloud.githubusercontent.com/assets/6694067/19492850/b117e1c8-9578-11e6-8b3f-4243c997d293.png)

**Comment by vgrish** [comment]
https://github.com/bezumkin/miniShop2/pull/334

**Comment by Ibochkarev** [comment]
Fixed in #334
