### ISSUE TITLE
Ошибка в операциях сравнения параметра optionFilters

### ISSUE THREAD

**Issue by saeth** [modx-pro/miniShop2#255]
`$modx->runSnippet('msProducts', array(
    'optionFilters' => '{"area:>":50}'
));`
В подобном выражении аргументы "area" и "50" сравниваются как текстовые.

**Comment by CrazyBoy49z** [comment]
> `$modx->runSnippet('msProducts', array( 'optionFilters' => '{"area:>":50}' ));`
> В подобном выражении аргументы "area" и "50" сравниваются как текстовые.

У Вас была опция area?

`$modx->runSnippet('msProducts', array( 'optionFilters' => '{"size:>":50}' ));`
Протестировал работает

**Comment by Ibochkarev** [comment]
Не подтверждено
