### ISSUE TITLE
После добавления товара в корзину и обновления страницы товар в корзине увеличивается

### ISSUE THREAD

**Issue by andrconstruction** [modx-pro/miniShop2#256]
Собственно После добавления товара в корзину и обновления страницы товар в корзине увеличивается. Что по идее не должно быть так. Как я подозреваю, после добавление должен быть prg но этого не происходит или как-то неверно отрабатывают скрипты или я что неправильно сделал.

**Comment by Electrica** [comment]
Что то видать не верно сделал. Я не могу воспроизвести что то подобное
