### ISSUE TITLE
Добавление кнопки Обновления превью

### ISSUE THREAD

**Issue by Ibochkarev** [modx-pro/miniShop2#342]
### Резюме

Добавление кнопки Обновления превью

### Зачем это нужно?

Во вкладке галерея добавить кнопку Обновить превьюшки

### Предлагаемое решение(я)

Для удобства использования и обновления "превьюшек" необходимо добавить кнопку "Обновить превью"

### Связанные проблема(ы)/PR(ы)
NA

**Comment by webinmd** [comment]
было бы не плохо куда-то в настройках или в менюшку добавить кнопку Обновить ВСЕ превью, либо отдельным мини компонентом добавлять эту кнопку кому надо.

**Comment by vgrish** [comment]
Наверно речь о действиях?
- Обновить все
- Удалить все

В других случаях когда требуется выборочное обновление / удаление возвращаться к кнопке незачем.

**Comment by Ibochkarev** [comment]
@vgrish все верно.

**Comment by Ibochkarev** [comment]
Добавлено в #347
