### ISSUE TITLE
Баг при сохранение заказа и смене статуса

### ISSUE THREAD

**Issue by webinmd** [modx-pro/miniShop2#346]
### Резюме

В админке, если редактировать заказ и затем изменять статус, то в письме юзеру/админу (если на статус стоит отправка уведомления) уходят старые данные, те что до сохранения были.

### Шаг для воспроизведения

Открыть заказ
Отредактировать
Сменить статус
Сохранить

На почту  получаем старые данные

### Ожидаемое поведение

По идее как в письме должны приходить только что измененные данные

### Среда

miniShop 2.4.18, MODX 2.7.1, php 7.0

**Comment by vgrish** [comment]
> уходят старые данные
что конкретно подразумевается под старыми данными?

можно пример привести, было, стало, получено...

**Comment by webinmd** [comment]
> > уходят старые данные
> > что конкретно подразумевается под старыми данными?
> 
> можно пример привести, было, стало, получено...

Пример: 
На смену статуса включено уведомление юзеру.
Открываю заказ, дописываю в поле "комментарий"  данные по трекингу, меняю статус заказа на Отправлено, сохраняю. 
Юзер получает письмо, но поле комментарий пустое, как было до сохранения. 
Если же вписать комментарий, сохранить, обновить страницу и после этого менять статус, то в письме поле комментарий уже заполнено как нужно.

**Comment by Ibochkarev** [comment]
Исправлено в #348
