### ISSUE TITLE
Меняется категория товара при сортировке мышкой

### ISSUE THREAD

**Issue by AlexSus** [modx-pro/miniShop2#354]
### Резюме
Если открыть общую категорию товаров, например у нас есть главная категория **Каталог**, а в ней уже несколько дочерних, и у нас включено **Показывать вложенные товары** и при попытке в этой главной категории пересортировать товары, то у товара, которые переносится меняется категория.

### Шаги для воспроизведения

Создаем родительскую категорию **Каталог**, в ней создаем еще 2 категории **Обувь** и **Штаны**, в каждой из дочерних категорий создаем по одному товару. Открываем категорию **Каталог**, по умолчанию стоит галочка **Показывать вложенные товары** и мы видим все товары из дочерних категорий. Пытаемся один товар поставить выше другого.

![изображение](https://user-images.githubusercontent.com/24259648/64725308-8d5d6280-d4fe-11e9-9a8e-ec3397cfa774.png)

### Наблюдаемое поведение

У товара, который мы переносим мышкой, сменится категория на ту, чей товар будет ближе, где мы отпускаем мышку:

![изображение](https://user-images.githubusercontent.com/24259648/64725380-aa923100-d4fe-11e9-9dcb-b1293f8dbdc6.png)

Здесь я решил перенести **Обувь1** выше **Штаны1**

### Ожидаемое поведение

Должна была смениться только сортировка menuindex, категория не должна меняться. Это довольно неочевидное поведение.

### Среда

Версия miniShop2 2.5.0, версия MODX 2.7.1, php 7.2, хостинг modhost, браузер Firefox последней версии.

**Comment by iWatchYouFromAfar** [comment]
Подтверждаю, баг есть. До обновления 2.5.0 такой проблемы не возникало.

**Comment by AlexSus** [comment]
> Подтверждаю, баг есть. До обновления 2.5.0 такой проблемы не возникало.

Вынужден не согласиться, изначально обнаружил проблему на 2.4.14-pl.
Это я просто для того, чтобы убедиться не поправили ли на последней версии, протестировал на ней и указал её.

**Comment by iWatchYouFromAfar** [comment]
> > Подтверждаю, баг есть. До обновления 2.5.0 такой проблемы не возникало.
> 
> Вынужден не согласиться, изначально обнаружил проблему на 2.4.14-pl.
> Это я просто для того, чтобы убедиться не поправили ли на последней версии, протестировал на ней и указал её.

Да верно, на 2.4.18-pl протестировал - баг уже был.

**Comment by Ibochkarev** [comment]
@GulomovCreative Не поможешь?

**Comment by GulomovCreative** [comment]
Понятно, что выглядит никак иначе как баг, но это всё таки фича

https://github.com/bezumkin/miniShop2/blob/0a0625a6a5aa27cabb73051e2c5b818999cd9f60/core/components/minishop2/processors/mgr/product/sort.class.php#L26-L32

Сортировка ресурсов находящихся в разных категориях с помощью перетаскивания не совсем логична. Пример:

* Каталог
  - Категория 1
    - Товар 1 (index: 70)
    - Товар 2 (index: 80)
  - Категория 2
    - Товар 3 (index: 10)
    - Товар 4 (index: 20)

Если переместить Товар 4 между товарами 1 и 2 (но фактически на Товар 1) то он получит index 71, ожидаемо было бы решить, что теперь наш товар выше своего соседа (Товар 3), но с index-ом 71 он всё еще после (ниже) Товара 3.

И именно поэтому в процессоре сортировки проверяется(ются) перетаскиваемый(е) ресурс(ы) и ресурс на котором отпустили (т.е. target), если их родители одинаковые, то происходит сортировка, а если родители разные, то запускается метод move, т.е. эта фича :)
https://github.com/bezumkin/miniShop2/blob/0a0625a6a5aa27cabb73051e2c5b818999cd9f60/core/components/minishop2/processors/mgr/product/sort.class.php#L31

https://github.com/bezumkin/miniShop2/blob/0a0625a6a5aa27cabb73051e2c5b818999cd9f60/core/components/minishop2/processors/mgr/product/sort.class.php#L84-L89

**Comment by AlexSus** [comment]
Может быть тогда запретить перетаскивание в родительских категориях или когда включена галочка **Показывать вложенные товары**? Я как раз и столкнулся с этим поведением, когда менеджер захотел рассортировать 30 товаров из 3 категорий и у него никак не получалось, еще и категории сбивались, пришлось вручную у каждого товара проставлять menuindex.

В идеале может быть, чтобы у всех товаров был один общий индекс, а не отдельный в каждой категории? Или может отдельное поле, где будет храниться общий индекс всех товаров.

**Comment by GulomovCreative** [comment]
> Может быть тогда запретить перетаскивание в родительских категориях или когда включена галочка Показывать вложенные товары?

Вот эту идею в виде решения в первую очередь можно рассматривать

> В идеале может быть, чтобы у всех товаров был один общий индекс, а не отдельный в каждой категории?

А вы знали?) Именно так и есть, у каждого товара/ресурса есть одно поле menuindex и его используют в качестве индекса сортировки.

Я в примере выше описал случай когда такая сортировка невозможна с помощью одного поля. Решение может быть в виде создания таблицы где хранились бы индексы для всех категорий по отдельности
