### ISSUE TITLE
Улетающее за границы экрана окно заказа

### ISSUE THREAD

**Issue by AnToHu0** [modx-pro/miniShop2#356]
В нескольких магазинах регулярно случается такой баг: в списке заказов при открытии окошка заказа иногда шапка формы улетает наверх за границы окна браузера. Почему это происходит - не понятно, приходится авторизовываться под соответствующим клиентом, лезть в инструменты разработчика и возвращать свойству css top положительное значение. Может можно сделать какое-то строгое ограничение для значения css свойства top для этого окошка, чтоб оно выше границы экрана не могло оказаться?

**Comment by vgrish** [comment]
пускай каждый менеджер авторизовывается под своим аккаунтом и проблем не будет.

**Comment by AnToHu0** [comment]
И так каждый под своим. У них слетает и мне приходится логиниться под нужный акк и править стили в браузере.

**Comment by vgrish** [comment]
Пока что у меня версия что кто-то с устройством большего разрешения авторизуется в админке, а затем под данным аккаунтом авторизуются на устройстве с меньшим разрешением и получается подобный глюк. 
Опишите сценарий воспроизведения.

**Comment by AnToHu0** [comment]
Я тоже грешу на это, но меня прямо уверяли, что менеджеры всегда за одним и тем же рабочим местом сидят.
Сам воспроизвести не могу, оно, как всегда "само, я ничего не трогала".
Если бы знал, то в первом посте сразу написал.

В любом случае, решением может быть запрет отрицательной вертикальной координаты окошка, ибо я не представляю кейса, при котором это окно надо уводить на верх за пределы экрана.

**Comment by vgrish** [comment]
попробуйте добавить после этой строчки https://github.com/bezumkin/miniShop2/blob/master/assets/components/minishop2/js/mgr/misc/default.window.js#L25
```
this.on('afterrender', function () {
   this.center();
});
```

понаблюдайте, возможно это решит проблему.

**Comment by AnToHu0** [comment]
Да, теперь вроде при любом раскладе в центре появляется.

**Comment by vgrish** [comment]
> Да, теперь вроде при любом раскладе в центре появляется.

Отлично, если будут еще косяки подобного плана отпишите тут, если все норм, то в след. обновлении пакета добавлю эту правку.

**Comment by AnToHu0** [comment]
Вроде всё ок, закрываю. Если вдруг всплывёт что, напишу.
