### ISSUE TITLE
У товара, на вкладке "Категории" не отображаются категории, если они вложены в другой ресурс (не категория)

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modx-pro/miniShop2#360]
## Сообщение об ошибке
Во вкладке "Категории" у товара дерево категорий отображается при `'isfolder' => true` (https://github.com/bezumkin/miniShop2/blob/master/core/components/minishop2/processors/mgr/category/getnodes.class.php#L60).
Однако в MODX при перетаскивании ресурсов в другой - isfolder не всегда станет true, думаю, нужно другой фильтр добавить, чтобы отображать только категории без других ресурсов.

Категория была во вложенном ресурсе, но у ресурса isfolder false, и я ее не мог выбрать.

![category](https://user-images.githubusercontent.com/12523676/65323499-94e5d100-dbba-11e9-8871-542a555dded4.png)

### Резюме
**По-моему, тут должно отображаться только дерево категорий и все, без других ресурсов.**

p.s. Еще чекбоксы у категорий без стилей, красивее сделать иконочный чекбокс.

В итоге, при учете того, что в дереве отображаются только категории, то нам не нужны иконки категорий в дереве, а дерево будет, например, таким:

![category_f](https://user-images.githubusercontent.com/12523676/65362827-01dc8380-dc1a-11e9-8b45-c2c364565372.png)

Кстати, почему-то в дереве категорий контекст отображается через ключ, а логичнее через имя контекста.

### Среда
miniShop2 2.5
MODX 2.7.1

**Comment by GulomovCreative** [comment]
> Кстати, почему-то в дереве категорий контекст отображается через ключ, а логичнее через имя контекста.

Вот это отличная идея, сделаю чтобы при существовании имени оно выводилось

**Comment by Ibochkarev** [comment]
Сделано в #364

**Comment by webinmd** [comment]
В miniShop 4.2.0 MODX 2.8.5  не воспроизводится, так как изменилась логика построения дерева.
