### ISSUE TITLE
Сменить иконки у категории и товара в дереве

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modx-pro/miniShop2#361]
## Запрос функции

В нынешнем варианте, как мне кажется, иконки не очень понятные. В FontAwesome есть лучше.
Вопрос не принципиальный, но с новыми иконками понятнее и красивее :)

Предлагаю поменять иконки на новые:
- для категории - на `icon icon-cubes`
- для товара - на `icon icon-cube`

**Новый вариант:**

![icons_2](https://user-images.githubusercontent.com/12523676/65324870-7aadf200-dbbe-11e9-8627-7e1898f8e191.png)

**Старый вариант:**

![icons_1](https://user-images.githubusercontent.com/12523676/65324861-75e93e00-dbbe-11e9-9daf-d5751b2102a3.png)

Еще в кнопках также стоит брать иконки из "Системных настроек", сейчас же они прописаны в коде

![icons_3](https://user-images.githubusercontent.com/12523676/65324871-7aadf200-dbbe-11e9-9418-b54cfc2c4cb4.png)

**Comment by Electrica** [comment]
По мне как то смыса нет. Штрихкод идет еще с первой версии минишопа. Мне кажется это логичнее, чем коробка, или куб.

**Comment by Ruslan-Aleev** [comment]
Ну это я для обсуждения разместил, не вот вопрос важный. Можно обсудить, если нет, то и ладно :)

**Comment by Ruslan-Aleev** [comment]
Ну, кстати, иконка штрих-кода лично меня сначала смущала, по-первой это иконка выглядела "непрогрузившейся" какой-то, пока я ее класс не увидел `icon icon-barcode` и не понял, что это штрих-код оказывается.

**Comment by Electrica** [comment]
Ну кубики тож конечно далеко не идеал )))

**Comment by Electrica** [comment]
![image](https://user-images.githubusercontent.com/3878386/65330943-8ceb5880-dbdd-11e9-9dec-1310e501cc25.png)
вот такое что то, тут хотя бы будет логичнее

**Comment by Ruslan-Aleev** [comment]
Я предложил кубы (коробки), чтобы логика была, типа "Элементы (категория) - Элемент (продукт)". Визуальная связь категории и продукта (несколько сущностей - одна сущность).

Да и коробки - это тоже к товару можно отнести, а так понятно, что есть прям корзина магазинная, но связь категории и товара не будет прослеживаться.

**Comment by iWatchYouFromAfar** [comment]
Считаю немного излишней данную правку. Каждый может поменять иконки самостоятельно, под свои вкусы и нужды.

**Comment by GulomovCreative** [comment]
> Еще в кнопках также стоит брать иконки из "Системных настроек", сейчас же они прописаны в коде

Вот это можно будет реализовать

**Comment by Ibochkarev** [comment]
Сделано в #365
