### ISSUE TITLE
Count в корзине

### ISSUE THREAD

**Issue by OlegShchavelev** [modx-pro/miniShop2#362]
## Запрос функции

Здорово было доработать count в базовом шаблоне оформление заказа. 

### Резюме

1. Запретить возможность прокручивать колесиком мышки.
2. Минимальное значение != 0 (сейчас удаление товара). 
3. Добавить кнопки + и - 

### Зачем это нужно?

Здесь несколько мативиций зачем это нужно:

1. У многих модулей интернет-магазина это уже реализованно.
2. Очень часто используется в разработке.
3. Это важно для каждого проекта. Так как мелкие задачи не очевидны всем участникам проекта и их легко упустить.

**Comment by webinmd** [comment]
_Запретить возможность прокручивать колесиком мышки._

Что имеется ввиду? в поле count запретить прокручивать мышкой?

**Comment by OlegShchavelev** [comment]
Совершенно верно. Еще одно уточнение. К примеру в Google Chrome изменить значение количетсво товара прокручиванием колесика мышки нельзя, а в firefox можно.

**Comment by webinmd** [comment]
> Совершенно верно. Еще одно уточнение. К примеру в Google Chrome изменить значение количетсво товара прокручиванием колесика мышки нельзя, а в firefox можно.

Не очень понимаю чем это мешает, но если что, это гуглится за 2 минуты.
Во всяком случае можно обсудить этот функционал, так как менять родное поведение инпута/селекта и прочих элементов форм не всегда хорошо и приносить привычное поведение в жертву дизайнерам не хотелось бы.

```
// Disable Mouse scrolling
$('input[type=number]').on('mousewheel',function(e){ $(this).blur(); });

// Disable keyboard scrolling
$('input[type=number]').on('keydown',function(e) {
    var key = e.charCode || e.keyCode;
    // Disable Up and Down Arrows on Keyboard
    if(key == 38 || key == 40 ) {
	e.preventDefault();
    } else {
	return;
    }
});

// THEN DISABLE ARROWS IN CSS
// input[type=number]::-webkit-inner-spin-button, 
// input[type=number]::-webkit-outer-spin-button { 
//   -webkit-appearance: none; 
//   margin: 0; 
// }
```

**Comment by OlegShchavelev** [comment]
> Не очень понимаю чем это мешает, но если что, это гуглится за 2 минуты.
> Во всяком случае можно обсудить этот функционал, так как менять родное поведение инпута/селекта и прочих элементов форм не всегда хорошо и приносить привычное поведение в жертву дизайнерам не хотелось бы.

Идея написать все мысли в комлексе про count. Сейчас случайном движением колесиком мышки можно удалить товар из оформления заказа. Я решил разделить данную проблему на два пункта. Еще один довод что любое изменение колочества заказа информируется сообщением jgrowl . Тем самым мы получаем большое количетсво сообщений. 

Первично кнопка + и - остальные предложения как-то пощелкал корзину и решил написать)

**Comment by iWatchYouFromAfar** [comment]
> ## Запрос функции
> Здорово было доработать count в базовом шаблоне оформление заказа.
> 
> ### Резюме
> 1. Запретить возможность прокручивать колесиком мышки.
> 2. Минимальное значение != 0 (сейчас удаление товара).
> 3. Добавить кнопки + и -
> 
> ### Зачем это нужно?
> Здесь несколько мативиций зачем это нужно:
> 
> 1. У многих модулей интернет-магазина это уже реализованно.
> 2. Очень часто используется в разработке.
> 3. Это важно для каждого проекта. Так как мелкие задачи не очевидны всем участникам проекта и их легко упустить.

Как не пытался в FF прокрутить колесиком - не получается. Ну это ладно... Все что вы описали - не очень будет уместно, т.к. сейчас из коробки идет сырой input, который можно легко кастомизировать под нужды шаблона.

Если вы это делает на каждом проекте, то у вас наверняка уже есть наработки, которые применяются за считанные пару-тройку минут. Мое мнение - не стоит вносить изменения подобного типа.

Тестировал [тут](https://minishop2.com/cart).

**Comment by webinmd** [comment]
> Все что вы описали - не очень будет уместно, т.к. сейчас из коробки идет сырой input, который можно легко кастомизировать под нужды шаблона.
> 
> Если вы это делает на каждом проекте, то у вас наверняка уже есть наработки, которые применяются за считанные пару-тройку минут. Мое мнение - не стоит вносить изменения подобного типа.

На самом деле это приходится делать в 90% проектов, НО дизайнеры каждый раз рисуют по разному, то сбоку в виде стрелок, то плюсы/минусы, то разносят по бокам плюс и минус, то еще  что-то, переделывать под какой-то дизайн потом окажется сложнее, чем стилизовать голый input.

**Comment by iWatchYouFromAfar** [comment]
> > Все что вы описали - не очень будет уместно, т.к. сейчас из коробки идет сырой input, который можно легко кастомизировать под нужды шаблона.
> > Если вы это делает на каждом проекте, то у вас наверняка уже есть наработки, которые применяются за считанные пару-тройку минут. Мое мнение - не стоит вносить изменения подобного типа.
> 
> На самом деле это приходится делать в 90% проектов, НО дизайнеры каждый раз рисуют по разному, то сбоку в виде стрелок, то плюсы/минусы, то разносят по бокам плюс и минус, то еще что-то, переделывать под какой-то дизайн потом окажется сложнее, чем стилизовать голый input.

Я и говорю, что лучше оставить как есть. Функционал кнопок меняется легко через JS, вид через обычную верстку.

**Comment by GulomovCreative** [comment]
Добавим атрибут min со значением 1 для input.count в стандартном чанке корзины, всё остальное к сожалению "нагромождение", но всё равно спасибо @DetaliDigital

**Comment by CrazyBoy49z** [comment]
> 3\. Добавить кнопки + и -

Предлагаю сделать из коробки. В проектах которых делал на 100% было нужно
