### ISSUE TITLE
Форматирование цены в карточке товара

### ISSUE THREAD

**Issue by Electrica** [modx-pro/miniShop2#363]
## По идее форматирование цены в карточке и в выводе товаров должно быть одно

Сейчас в выводе товаров идет 135 000 а в самой карточке 135000 слитно

**Comment by webinmd** [comment]
{$price | number : 0 : '.' : ' '}

**Comment by Electrica** [comment]
В данный момент человек ставит miniShop2. Нет никаких феномов и прочего, все стандартно. И он не понимает, почему при выводе msProduct у него цена 135 520 а в карточке 135520. Может это все привести к одному формату везде?

**Comment by webinmd** [comment]
> В данный момент человек ставит miniShop2. Нет никаких феномов и прочего, все стандартно. И он не понимает, почему при выводе msProduct у него цена 135 520 а в карточке 135520. Может это все привести к одному формату везде?

Зашёл на тестовый сайт http://s19828.h10.modhost.pro/%D1%82%D0%B5%D1%81%D1%82-2.html 
Он абсолютно пустой, выставил цену и получил отформатированный вывод и в категории и в карточке товара

**Comment by GulomovCreative** [comment]
Дело в том, что в шаблоне [[*price]] выводит без, а [[+price]] с форматированием

**Comment by webinmd** [comment]
> Дело в том, что в шаблоне [[*price]] выводит без, а [[+price]] с форматированием

я использовал {$price}

**Comment by Electrica** [comment]
Еще раз, без какого либо фенома, на стандартных phx шаблонизаторе.

**Comment by Electrica** [comment]
В сниппете проходит форматирование через метод :
https://github.com/bezumkin/miniShop2/blob/master/core/components/minishop2/elements/snippets/snippet.ms_products.php#L193
А вот получается что в шаблоне выводет на прямую данные, а там они как раз не форматированные

**Comment by webinmd** [comment]
> Еще раз, без какого либо фенома, на стандартных phx шаблонизаторе.

В стандартном чанке **msProduct.content** написано
 [[+price]] [[%ms2_frontend_currency]]

это выводит цену отформатированной. 
Баха правильно написал
[[+price]] - отформатированная цена (плейсхолдер подготовленный минишопом)
[[*price]] - не отформатированная (плейсхолдер подготовленный по умолчанию)

То есть на странице карточки ты можешь использовать [[+price]] для получения отформатированного вывода

**Comment by GulomovCreative** [comment]
Спасибо @Electrica
