### ISSUE TITLE
В оформление заказа в предитог добавить сумма без доставки и стоимость доставки 

### ISSUE THREAD

**Issue by OlegShchavelev** [modx-pro/miniShop2#366]
## Запрос функции

Здорово было в стандартном шаблоне вывести два плейсхолдера с обновлением на лету:

- стоимость без доставки
- стоимость доставки

### Зачем это нужно?

Лично для меня проблем нет. Наследуем класс и несколько строчек JS и готово. Но мне кажется штука очень распространненая часто используется и здорово вывести их в шаблоне по умолчанию.

**Comment by Electrica** [comment]
Это на самом деле просто делается через расширение класса https://github.com/bezumkin/miniShop2/blob/master/core/components/minishop2/model/minishop2/msorderhandler.class.php#L544

по документации:
https://docs.modx.pro/komponentyi/minishop2/razrabotka/sluzhbyi/zakaz

но в общем я согласен нужна такая тема из коробки

**Comment by supernacho89** [comment]
Да. Интересно и давно нужно.

**Comment by OlegShchavelev** [comment]
> Это на самом деле просто делается через расширение класса https://github.com/bezumkin/miniShop2/blob/master/core/components/minishop2/model/minishop2/msorderhandler.class.php#L544
> 
> по документации:
> https://docs.modx.pro/komponentyi/minishop2/razrabotka/sluzhbyi/zakaz
> 
> но в общем я согласен нужна такая тема из коробки

Спасибо, что в комментарий добавил референсы. Я как-то не подумал что кому-то они будут полезны. Буду прикреплять к предложениям в следующий раз.

**Comment by Ibochkarev** [comment]
Добавлено в #507
