### ISSUE TITLE
Изменить порядок вкладок в товаре

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modx-pro/miniShop2#367]
### Резюме
В нынешнем варианте miniShop2 у товара часто используемые вкладки разделены редко используемыми, например, вкладка "Галерея" стоит после "Группы ресурсов".

Было бы полезным изменить порядок вкладок по частоте использования - станет полезнее для UX.

Вот как я вижу новый порядок вкладок:

![tabs](https://user-images.githubusercontent.com/12523676/65493761-8c481000-dec4-11e9-8ec8-49eef0c942da.png)

p.s. Возможно эти вкладки только меня смущают, нужно обсуждение :)

**Comment by GulomovCreative** [comment]
А вот это уже может сделать компонент, нужно обсудить

**Comment by Ibochkarev** [comment]
Сделано в #376
