### ISSUE TITLE
Нумерация заказа MS2

### ISSUE THREAD

**Issue by OlegShchavelev** [modx-pro/miniShop2#370]
## Запрос функции

Предлагаю в настройки Minishop2 добавить настройки вариации нумерации заказа [getNum()](https://github.com/bezumkin/miniShop2/blob/master/core/components/minishop2/model/minishop2/msorderhandler.class.php#L592)

За основу я взял документацию интернет-магазина Битрикса имеющие гибкие настройки управления номером [заказа](https://dev.1c-bitrix.ru/community/blogs/product_features/orders_numeration.php):

**Задача №1**

Сделать настройку для изменения порядкового номера заказа.

**Зачем?**

Пользователи системы после переезда с другой системы на MODX CMS с интернет-магазином MS2 просят сделать номер заказа с определенного номера. Так как полагают, что если покупатель увидит номер 2 или 3 в заказе будут испытывать не доверие или дискомфорт.

**Задача №2** 

Реализовать возможность выбора формата нумерации, в том числе:

-  случайный уникальный номер  2002/543567 **или** 543567
-  нумерация за определённый период 24062013/5 **или** 062013/4 **или** 2013/3
-  порядковый номер заказа 566

**Задача №3** 

Реализовать возможность устанавливать префикс в начале номера для любого из варианта номера:

OL-2002/543567 **или** OL-543567 
OL-24062013/5 **или** OL-062013/4 **или** OL-2013/3
OL-566

К примеру такая идея уже есть в пакете mvtForms 

![изображение](https://user-images.githubusercontent.com/20732384/73979975-5752cc00-4940-11ea-984a-824c5f237261.png)

### Расшифровка даты

**Нумерация за определённый период**

В пределах дня: 24062013 / 5
В пределах месяца: 062013 / 4
В пределах года:  2013 / 3

**случайный уникальный номер**

Год и месяц:  2002/543567 

Зачем? Клиенту трактуют по-разному. Как правило, клиенты просят изменить номер заказа для не возможности определения заказа лицом анализирующий торговую нишу с целью определения количества заказов. А кому-то хочется простой порядковый номер, как стереотип "зачем мудрить".

**Comment by CrazyBoy49z** [comment]
Хорошая идея, если нужно могу набросать.

**Comment by Ibochkarev** [comment]
> Хорошая идея, если нужно могу набросать.

Давай =)

**Comment by Sentinel-7** [comment]
И еще бы хорошо сделать возможность убирать слеш у заказа.

**Comment by CrazyBoy49z** [comment]
@Sentinel-7 спасибо за обращение, сейчас Олег детально напишет что нужно и в каких вариациях переделаю.

**Comment by OlegShchavelev** [comment]
Я тут переформулировал. Можем обсуждать. Я готов ответить на все ваши вопросы))

**Comment by Sentinel-7** [comment]
Да в принципе все круто, что тут обсуждать, если все три варианта реализуют, то будет Агонь! 🙂🙂

**Comment by OlegShchavelev** [comment]
@Sentinel-7 @CrazyBoy49z будет очень стараться сделать Огонь мы в него все верим.

**Comment by Ibochkarev** [comment]
Добавлено в #393
