### ISSUE TITLE
Сортировка значений полей в админ-панели

### ISSUE THREAD

**Issue by Arahort** [modx-pro/miniShop2#371]
## Запрос функции
Добавить возможность сортировать значения полей таких как Цвет, Размер и т.д. путём drag-and-drop'а

### Зачем это нужно?
Сильно не хватает возможности вручную выставлять порядок Цвета, Размера и других полей в админке, во фронтенде параметры выводятся в том же порядке что и в админке и если мы используем например msOptionPrice для связи цены с конкретным цветом например, то хотелось бы вручную управлять их порядком, например у одного товара первым что бы был цвет Х и соответственно по умолчанию тогда будет отображаться цена Х, а у другого товара выбрать по умолчанию цвет Y, следовательно у него будет по умолчанию цена Y. Или же например добавленные менеджером возможные размеры товара захотелось потом выставить в порядке по возрастанию размера, удалять и добавлять снова -такое себе, всё это пытаться сортировать как тебе надо при выводе тоже тот ещё гемор.

![1569496039680](https://user-images.githubusercontent.com/24698143/65683836-fc8e9700-e066-11e9-809a-f85137e7776b.png)

**Comment by webinmd** [comment]
@Arahort не это ?  #345

**Comment by vgrish** [comment]
реализовано https://github.com/bezumkin/miniShop2/pull/345
