### ISSUE TITLE
Добавить несколько миниатюр по умолчанию для галерей

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modx-pro/miniShop2#375]
### Резюме
По умолчанию в источнике файлов галереи сейчас стоит одна миниатюра, однако лучше добавить несколько.

### Зачем это нужно?
1) Сам ошибался и в чате видел, что люди по-невнимательности не правильно пишут json с миниатюрами, а если их будет несколько - ошибиться труднее.
2) Чаще всего для магазина всегда нужны более одной миниатюр, и править их в итоге будет проще, чем с нуля создавать.

**Comment by webinmd** [comment]
Получается просто добавить в json еще значение?
```
{
"small":{"w":100,"h":100,"q":90,"zc":"1","bg":"000000"},
"medium":{"w":400,"h":300,"q":90,"zc":"1","bg":"000000"}
}
```
Не уверен что это необходимо изначально, будет в 2 раза больше лишних файлов. 
С другой стороны если проблема реально есть, то можно и дать более полный пример

**Comment by Ibochkarev** [comment]
@webinmd Я за пример!
А также добавить пример формирования c `webp`
