### ISSUE TITLE
Удаление товаров (более 50 позиций за раз)

### ISSUE THREAD

**Issue by OlegShchavelev** [modx-pro/miniShop2#382]
## Сообщение об ошибке

Некоректно работает функция удаления несколько товаров

### Резюме
 
1. При выборе в каталоге большого количество товаров для удаления (больше 50). После окончания процесса скрипта обновления страницы не происходит. После обновления страницы браузера все выбранные товары помечены на удаления. 
2. Процесс удаления товаров занимает много времени.

### Шаг для воспроизведения

1. Выбираем большой список товаров
2. Выделяем позиции которую необходимо удалить
3. В контекстном меню нажимаем кнопку удалить.
4. Идет заваривать кофе (желательно на 30 минут) обновляем страницу воля и все пометилось на удаление.

### Ожидаемое поведение

После окончания удаления страница обновляется автоматически аналогично если мы удаляем 2-3 товара.

### Среда

MS2 2.5.1 PHP 7.1 MODx 2.7.1 NGINx Apache2 MySQL 5.7

**Comment by webinmd** [comment]
Поведение минишопа при удалении товаров зависит от параметров вашего хостинга/сервера. 
Повторив шаги воспроизведения на обычном шаред хостинге  (beget), получил удаление 70 товаров за ~ 15 секунд с последующим обновлением таблицы товаров и пометкой товаров как удаленных. 

![eNHWqxoYAh](https://user-images.githubusercontent.com/966234/68945161-61898200-07b8-11ea-8c4f-ccddb9bd2b75.gif)

**Comment by OlegShchavelev** [comment]
Наверное я все таки не правильно указал минимальное количество. У меня зависло при удаление 300 товаров. Потом позвонил ответсвенному лицу спросить что и как получил рекомендацию что удалять нужно не более чем по 50 позиций (так как может зависнуть).

Я сегодня тогда подготовлю видео с консолью и настройками хостина (хостинг мощный тариф VIP с 1024Mb оперативки)

**Comment by Ibochkarev** [comment]
Сегодня удалял 800 товаров на сайте, баг не обнаруживается.
