### ISSUE TITLE
Дополнительные поля msVendor

### ISSUE THREAD

**Issue by OlegShchavelev** [modx-pro/miniShop2#383]
## Сообщение об ошибке

Я не уверен что это ошибка. Но было здорово сформулировать это в документации, мы станем лучше, а мир более понятней.

### Резюме

Я хочу добавить в настрйках два дополнительных поля 

- краткое описание
- галочка "Включить в название товара бренд и коллекцию" (это нужно для задач по оптимизации название скажем не имеет значение)

### Шаг для воспроизведения

Добавим плагин с JS где мы наследуем наш скрипт ExtJS где мы генерируем расширенную форму (у меня несколько JS файлов первый для расширения формы заказа)

```
<?php
switch ($modx->event->name) {
    case 'msOnManagerCustomCssJs':
        switch ($page) {
            case 'orders':
            $modx->controller->addLastJavascript(MODX_ASSETS_URL . 'components/minishop2/custom/addjsms2.js');
            break;
            case 'settings':
            $modx->controller->addLastJavascript(MODX_ASSETS_URL . 'components/minishop2/custom/addjsms2vendor.js');
            break;
        }
        break;
}
```

Событие **msOnManagerCustomCssJs**

Насдедуем форму и расширем дополнительные поля

```
Ext.override (miniShop2.window.CreateVendor, {
    getFields: function (config) {
        return [
            {xtype: 'hidden', name: 'id', id: config.id + '-id'},
            {
                layout: 'column',
                items: [{
                    columnWidth: .6,
                    layout: 'form',
                    defaults: {msgTarget: 'under'},
                    items: [{
                        xtype: 'textfield',
                        fieldLabel: _('ms2_name'),
                        name: 'name',
                        anchor: '99%',
                        id: config.id + '-name'
                    }],
                }, {
                    columnWidth: .4,
                    layout: 'form',
                    items: [{
                        xtype: 'textfield',
                        fieldLabel: _('ms2_country'),
                        name: 'country',
                        anchor: '99%',
                        id: config.id + '-country'
                    }],
                }]
            }, {
                layout: 'column',
                items: [{
                    columnWidth: .4,
                    layout: 'form',
                    items: [{
                        xtype: 'textfield',
                        fieldLabel: _('ms2_email'),
                        name: 'email',
                        anchor: '99%',
                        id: config.id + '-email'
                    }],
                }, {
                    columnWidth: .6,
                    layout: 'form',
                    items: [{
                        xtype: 'minishop2-combo-resource',
                        fieldLabel: _('ms2_resource'),
                        name: 'resource',
                        anchor: '99%',
                        id: config.id + '-resource'
                    }],
                }]
            }, {
                xtype: 'minishop2-combo-browser',
                fieldLabel: _('ms2_logo'),
                name: 'logo',
                anchor: '99%',
                id: config.id + '-logo'
            }, {
                xtype: 'textarea',
                fieldLabel: _('ms2_address'),
                name: 'address',
                anchor: '99%',
                id: config.id + '-address'
            }, {
                layout: 'column',
                items: [{
                    columnWidth: .5,
                    layout: 'form',
                    items: [{
                        xtype: 'textfield',
                        fieldLabel: _('ms2_phone'),
                        name: 'phone',
                        anchor: '99%',
                        id: config.id + '-phone'
                    }],
                }, {
                    columnWidth: .5,
                    layout: 'form',
                    items: [{
                        xtype: 'textfield',
                        fieldLabel: _('ms2_fax'),
                        name: 'fax',
                        anchor: '99%',
                        id: config.id + '-fax'
                    }],
                }]
            }
            
            , {
                xtype: 'textarea',
                fieldLabel: _('ms2_dtls_introtext'),
                name: 'dtls_introtext',
                anchor: '99%',
                id: config.id + '-dtls_introtext'
            }
            
            , {
                xtype: 'textarea',
                fieldLabel: _('ms2_description'),
                name: 'description',
                anchor: '99%',
                id: config.id + '-description'
            }
            
            ,
            
            {
                xtype: 'xcheckbox',
                boxLabel: _('ms2_dtls_active'),
                name: 'dtls_active',
                anchor: '99%',
                id: config.id + '-dtls_active',
                
            }
        ];
    }
});
```

Далее регистрируем плагин и подключаем файл маппинга и заведем поля в БД в таблицу msvendor

```
<?php
return array(
    'map' => array(
        'msVendor' => require_once 'msvendor.map.inc.php',
    ),
);
```

Добавляем маппинг

```
<?php
return array(
    'fields' => array(
        'dtls_introtext' => NULL,
        'dtls_active' => 1,
    ),
    'fieldMeta' => array(
        'dtls_introtext' => array(
          'dbtype' => 'text',
          'phptype' => 'string',
          'null' => NULL,
        ),
        'dtls_active' => array(
          'dbtype' => 'tinyint',
          'precision' => '1',
          'attributes' => 'unsigned',
          'phptype' => 'integer',
          'null' => true,
          'default' => 1,
        ),
    ),
);
```
В итоге данные отправляются в массив но поле по какой-то причине не сохраняются при повторном открытии.

**Скриншот массива данных после сохранения**

![GitHub img1](https://i.imgur.com/aA4INUy.png)
(url)

**Скриншот данных коннектора**

![GitHub img2](https://i.imgur.com/OwWQAHz.png)
(url)

### Наблюдаемое поведение

Данные передаются но не сохраняется в новых созданных полях.

### Ожидаемое поведение

Сохранение полей при нажатия кнопку "Сохранить"

### Среда

Версия miniShop2 2.5.0, версия MODX 2.7.2 , Apache/Nginx и версия, версия mysql 5.7 , браузер и т.д. Любая соответствующая информация.

**Comment by OlegShchavelev** [comment]
По такому принципу решил расширить форму опции. Зачем обязательно поделюсь, если будет удобно и конечно все получится.

Сделал по аналогии в табе опции. Все работает очень удобно кстати:
![Дополнительные в опциях](https://i.imgur.com/QMw1YGq.png)

**Comment by OlegShchavelev** [comment]
Спасибо @vgrish за комментарий у меня все заработало. Ссылка на пошаговую инстукцию как [это работает](https://modx.pro/howto/19257)

**Comment by CrazyBoy49z** [comment]
Я вот подумал может добавить ещё msVendors сниппет, чтобы на каждом проекте не писать его с нуля.
Например я всегда пишу быстрый вариант, но можно переписать под нормальную логику minishop
```
<?php
if (!isset($tpl)){
    $tpl = '';
}
if (!isset($limit)){
    $limit = 6;
}
$output  = [];
if ($pdoTools = $modx->getService('pdoTools')) {
    $pdoTools->addTime('pdoTools loaded.');
    $c = $modx->newQuery('msVendor');
    $c->limit($limit,0);

    $vendors = $modx->getIterator('msVendor', $c);
    $idx = 1;
    if (is_object($vendors)) {
        foreach ($vendors as $vendor) {
            $output[$idx] = $vendor->toArray();
            $idx++;
        }
    }
}
return $pdoTools->getChunk($tpl, ['output' => $output]);
```

**Comment by webinmd** [comment]
> Я вот подумал может добавить ещё msVendors сниппет, чтобы на каждом проекте не писать его с нуля.
> Например я всегда пишу быстрый вариант, но можно переписать под нормальную логику minishop
> 
> ```
> <?php
> if (!isset($tpl)){
>     $tpl = '';
> }
> if (!isset($limit)){
>     $limit = 6;
> }
> $output  = [];
> if ($pdoTools = $modx->getService('pdoTools')) {
>     $pdoTools->addTime('pdoTools loaded.');
>     $c = $modx->newQuery('msVendor');
>     $c->limit($limit,0);
> 
>     $vendors = $modx->getIterator('msVendor', $c);
>     $idx = 1;
>     if (is_object($vendors)) {
>         foreach ($vendors as $vendor) {
>             $output[$idx] = $vendor->toArray();
>             $idx++;
>         }
>     }
> }
> return $pdoTools->getChunk($tpl, ['output' => $output]);
> ```

```
{'pdoResources' | snippet: [
	'class' => 'msVendor',
	'tpl'  => '@FILE chunks/catalog/brand.tpl',
	'sortby' => 'id',
	'limit' => 0
]} 
```

**Comment by CrazyBoy49z** [comment]
> ```
> {'pdoResources' | snippet: [
> 	'class' => 'msVendor',
> 	'tpl'  => '@FILE chunks/catalog/brand.tpl',
> 	'sortby' => 'id',
> 	'limit' => 0
> ]} 
> ```

Спасибо что-то не подумал так сделать, но проблема остается только для тех кто не юзает fenom

**Comment by GulomovCreative** [comment]
> > ```
> > {'pdoResources' | snippet: [
> > 	'class' => 'msVendor',
> > 	'tpl'  => '@FILE chunks/catalog/brand.tpl',
> > 	'sortby' => 'id',
> > 	'limit' => 0
> > ]} 
> > ```
> 
> Спасибо что-то не подумал так сделать, но проблема остается только для тех кто не юзает fenom

Тут феном не причем, ничего не мешает написать на стандартном синтаксисе

**Comment by CrazyBoy49z** [comment]
> > > ```
> > > {'pdoResources' | snippet: [
> > > 	'class' => 'msVendor',
> > > 	'tpl'  => '@FILE chunks/catalog/brand.tpl',
> > > 	'sortby' => 'id',
> > > 	'limit' => 0
> > > ]} 
> > > ```
> > 
> > 
> > Спасибо что-то не подумал так сделать, но проблема остается только для тех кто не юзает fenom
> 
> Тут феном не причем, ничего не мешает написать на стандартном синтаксисе

Был в то время тупанул, недосыпание =)
