### ISSUE TITLE
Не отображаются категории после смены родительского документа

### ISSUE THREAD

**Issue by elec3c** [modx-pro/miniShop2#390]
### Резюме

После смены родительской категории они не отображаются в дереве ресурсов во вкладках:
1.  Вкладка 'Категории' в настройках товара
2. Вкладка 'Опции' в Настройках minishop2

### Шаг для воспроизведения

1 Создать документ в корне сайта.
2 Создать категорию в корне сайта.
3 Перетащить категорию в документ, созданный в шаге 1, так чтобы он стал для нее родительским.
4 Перейти в Пакеты -> Minishop2 -> Настройки -> Опции 
или создать товар в категории в настройках товара перейти на вкладку Товар -> Категории

В дереве ресурсов категория не видна.

Видео как воспроизвести
https://drive.google.com/open?id=1wmwqhAejZxxwTplnieCxfG_DcoQWxUcP

### Решение на скорую руку

Создание дополнительно дочернего документа сделает категории видимыми

### Среда

Версия miniShop2 2.5
Версия MODX 2.7.2

**Comment by Ruslan-Aleev** [comment]
Связано с https://github.com/bezumkin/miniShop2/issues/360
Проблема в `isfolder`

**Comment by GulomovCreative** [comment]
Считаю, что частично это баг самого MODXа

**Comment by Ruslan-Aleev** [comment]
@GulomovCreative баг-то есть в MODX, есть куча issue на эту тему.
Но для minishop2 можно запрос поменять, чтоб не было фильтра по `isfolder`.

**Comment by Ruslan-Aleev** [comment]
@vgrish Тут принципиально фильтровать по `isfolder` https://github.com/bezumkin/miniShop2/blob/master/core/components/minishop2/processors/mgr/category/getnodes.class.php#L60 ? Или можно строить **только** дерево категорий, используя, к примеру, `'class_key' => msCategory` ?

**Comment by GulomovCreative** [comment]
Отправил PR https://github.com/modxcms/revolution/pull/15076 в ядро MODX, если примут то и в 2.х решение отправлю

**Comment by Ibochkarev** [comment]
https://github.com/modxcms/revolution/pull/15076 влит. Будет доступен в 2.8.0.

issue закрываю.

@elec3c  Спасибо!
