### ISSUE TITLE
Ошибка при установке

### ISSUE THREAD

**Issue by topor-topor** [modx-pro/miniShop2#391]
### Резюме

При установке возникает ошибка создания таблицы ms2_options "Index column size too large. The maximum column size is 767 bytes."

Полный код ошибки:
```
Could not create table `JDWF4xPSBwzQ_ms2_options`
SQL: CREATE TABLE `JDWF4xPSBwzQ_ms2_options` (`id` INTEGER unsigned NOT NULL AUTO_INCREMENT, `key` VARCHAR(255) NOT NULL DEFAULT '', `caption` VARCHAR(255) NOT NULL DEFAULT '', `description` TEXT NULL, `measure_unit` TINYTEXT NULL, `category` INT(10) unsigned NOT NULL, `type` VARCHAR(255) NOT NULL DEFAULT '', `properties` TEXT NULL, PRIMARY KEY (`id`), INDEX `key` (`type`), FULLTEXT `caption_ft` (`caption`), INDEX `category` (`category`)) ENGINE=InnoDB
ERROR: Array
(
    [0] => HY000
    [1] => 1709
    [2] => Index column size too large. The maximum column size is 767 bytes.
)
```
Производилась обычная установка из менеджера пакетов.

Таблица создается только вручную если в запросе поменять VARCHAR(255) на VARCHAR(191).

### Среда

- Версия miniShop2: 2.5.0-pl
- Версия MODX: 2.7.2-pl
- Хостинг: TimeWeb
- Nginx 1.14 + Apache 2.4
- версия mysql: 5.6

**Comment by webinmd** [comment]
база utf8_general_ci или utf8_mb4_general_ci ?

**Comment by topor-topor** [comment]
utf8mb4_general_ci

**Comment by webinmd** [comment]
> utf8mb4_general_ci

есть ли возможность сменить кодировку для проверки установки?

**Comment by topor-topor** [comment]
Проверил. С кодировкой utf8_general_ci установился нормально.

**Comment by CrazyBoy49z** [comment]
Проблема в InnoDB, здесь инструкция как обойти "[Index column size too large. The maximum column size is 767 bytes.](https://blog.programs74.ru/mysql-and-error-index-column-size-too-large/)"
