### ISSUE TITLE
MODX 3 alpha1 не работает Minishop

### ISSUE THREAD

**Issue by OlegShchavelev** [modx-pro/miniShop2#392]
## Сообщение об ошибке

Связи с изменением ядра CMS MODX 3 alpha1 и требований к разработке компонентов текущая версия Minishop не запускается.

![n1ZVIjH](https://user-images.githubusercontent.com/20732384/71048316-11536600-2150-11ea-9be4-eb355548f9e3.png)

Но и получить пресс рилиз от комманды разработки компонента, какие планы у компонента в дальнейшем..

### Среда

Версия miniShop2 2.5.0 , версия MODX 3.0.0 alpha1

**Comment by Sentinel-7** [comment]
Привет
тут https://modx.pro/news/19512 Василий вроде все расписал

**Comment by OlegShchavelev** [comment]
> Привет
> тут https://modx.pro/news/19512 Василий вроде все расписал

@Sentinel-7. Привет! Тут не много другая история. Подробнее [по ссылке ](https://modx.pro/development/19443)
