### ISSUE TITLE
Неверный тип товара 

### ISSUE THREAD

**Issue by sssstudio** [modx-pro/miniShop2#394]
Приветствую!
в каких случаях возникает ошибка "Неверный тип товара" при попытке добавления в корзину ?
Ссылка для наглядности http://natator.ru/informacziya/bassejnyi/bassejn-pioner.html

**Comment by Ibochkarev** [comment]
@sssstudio https://modx.pro/help/7919 ознакомьтесь с решением. Ошибка не в miniShop2, а в ваших чанках.

**Comment by sssstudio** [comment]
Проблема в том что тот же шаблон здесь работает
 http://natator.ru/informacziya/bassejnyi/dom-sporta-miit-mgups.html

**Comment by webinmd** [comment]
> Проблема в том что тот же шаблон здесь работает
> http://natator.ru/informacziya/bassejnyi/dom-sporta-miit-mgups.html

Скорей всего у вас ресурс не является ТОВАРОМ.

**Comment by sssstudio** [comment]
Как это регламентируется и где, в таком случае?

**Comment by webinmd** [comment]
нужно дописать в документацию что ТОВАР должен быть ТОВАРОМ? 
О какой регламентации идет речь?
Минишоп добавляет 2 класса: Товар и Категория. 
Соответственно в корзину можно положить только ресурс у которого class_key = msProduct

**Comment by sssstudio** [comment]
Разобрались Благодарю
