### ISSUE TITLE
Исполнение ФЗ-152 в оформление заказа.

### ISSUE THREAD

**Issue by OlegShchavelev** [modx-pro/miniShop2#395]
## Запрос функции

Сделать в шаблоне по-умолчанию на странице "оформление заказа" галочку с валидацией подтверждающие ознакомления пользователей правилами обработки персональных данных 

### Зачем это нужно?

Это нужно для каждого проекта (России) и зачем делать если уже сделанно производителем (причем есть обсуждения как ее лучше делать) + информирование, что так принято.

### Предлагаемое решение(я)

Галочка нажата по-умолчанию, если снять то заказ невозможно отправить. По-умолчанию при устанвке MS2 галочку установленна как обязательная.

![изображение](https://user-images.githubusercontent.com/20732384/72686066-94762c00-3b01-11ea-86b7-91bc032617b3.png)

**Comment by iWatchYouFromAfar** [comment]
Давайте не перегружать систему (в данном случае компонент) подобного рода хотелками. Такие решения вообще не должны лежать в коробке, они рисуются дизайнерами, верстаются верстальщиками и натягиваются на MODx прямо из верстки.

**Comment by webinmd** [comment]
ну чего вы в самом деле? 
Предлагаете создавать автоматом и страницу с пользовательским соглашением?
Прописывать сразу ссылку на эту страницу в чанке?
А если такая страница уже существует? 
Вот эти вот манипуляции по сути нивелируют все плюсы если это будет сразу в коробке.
Делов на 3 минуты.
- создать ресурс
- добавить в чанк input с атрибутом required и внутри label вписать ссылку.

**Comment by OlegShchavelev** [comment]
Да, я обсолютно согласен 3 минуты (и даже трудности у многих не вызывет). А это единственные критерий обсуждения?
 
**Во-первых** у MS2 есть демо-версия у проекта. Она не подпадает под ФЗ-152? 
**Во-вторых** это хороший маркетинговый повод. Многие производители уже трубят об этом и их не смущает, что это всего 3 минуты. 
**В-третьих** даже по таким плевым темам, есть на modx.pro обсуждения, как это сделать, а значит есть аудитория кто будет этому благодарно. 

**К примеру Аспро Медицинский центр 2.0**

![изображение](https://user-images.githubusercontent.com/20732384/72687406-8aa6f580-3b0e-11ea-88d9-d2ce48dd145a.png)

**Comment by webinmd** [comment]
> В-третьих даже по таким плевым темам, есть на modx.pro обсуждения, как это сделать.

Боюсь что им уже ничем не поможешь.

Маркетинговый ход это добавить функционала хорошего, а не галочку. 
Ну а демо версию вообще по хорошему переделать. 
Одеть текущий функционал в красивый дизайн.

**Comment by iWatchYouFromAfar** [comment]
> Да, я обсолютно согласен 3 минуты (и даже трудности у многих не вызывет). А это единственные критерий обсуждения?
> 
> **Во-первых** у MS2 есть демо-версия у проекта. Она не подпадает под ФЗ-152?
> **Во-вторых** это хороший маркетинговый повод. Многие производители уже трубят об этом и их не смущает, что это всего 3 минуты.
> **В-третьих** даже по таким плевым темам, есть на modx.pro обсуждения, как это сделать, а значит есть аудитория кто будет этому благодарно.
> 
> **К примеру Аспро Медицинский центр 2.0**
> 
> ![изображение](https://user-images.githubusercontent.com/20732384/72687406-8aa6f580-3b0e-11ea-88d9-d2ce48dd145a.png)

Есть люди, которые компьютер иной раз не могут включить в сеть. Мы говорим все таки про продукт, который создан для разработчиков. Если разработчик не может один input добавить, то это не значит, что из-за таких людей нужно все в коробку пихать.

**Comment by bezumkin** [comment]
miniShop2 не только в РФ используют
