### ISSUE TITLE
Добавить клонирование опций в подкатегории

### ISSUE THREAD

**Issue by CrazyBoy49z** [modx-pro/miniShop2#398]
## Сообщение об ошибке
При создании подкаталога нет опций (не клонируются с родительского ресурса)

**Comment by VoiD2008** [comment]
У проблемы есть 3 решения.
1. это клонирование опций с родительской категории, решается комитом из #412 
2. проставлять новым товарам подкатегории принадлежность категориям выше по дереву
3. клонировать все опции вручную (фукнционал существует, кнопка скопировать в гриде опций)
