### ISSUE TITLE
Выборки в CMS Настройки MS2 -> во вкладке Опции по категориям(группам)

### ISSUE THREAD

**Issue by OlegShchavelev** [modx-pro/miniShop2#402]
## Запрос функции

Возможность в настройках MS2 во вкладке Опции добавить возможность выборку в интерфейсе выборки по категории (Группа). 

### Зачем это нужно?

Как правило, в каждом проекте опции от 200 до 1000 единиц. При контентных работах и разработки не хватает возможности сделать выборку по категории. На текущий момент выборку можно делать только по ресурсу - это не всегда удобно.

![изображение](https://user-images.githubusercontent.com/20732384/77491655-72758e80-6e4f-11ea-8bf8-c89124286847.png)

### Предлагаемое решение(я)

Предлагаю сделать селектор в котором выгружены все категории назначенные в опциях. При выборе определенной Категории(Группы) мы получаем опции принадлежащий этой группе.

![изображение](https://user-images.githubusercontent.com/20732384/77491829-eadc4f80-6e4f-11ea-9da7-e30a65f6bf8e.png)

**Comment by GulomovCreative** [comment]
@DetaliDigital Не совсем понимаю, что означает "выборка", ты про фильтрацию?

**Comment by OlegShchavelev** [comment]
> @DetaliDigital Не совсем понимаю, что означает "выборка", ты про фильтрацию?

Привет. Да именно фильтрацию.
