### ISSUE TITLE
Добавить для производителей поле псевдоним

### ISSUE THREAD

**Issue by webinmd** [modx-pro/miniShop2#409]
## Запрос функции
Добавить для производителей поле "псевдоним" (alias)

### Зачем это нужно?

Удобно было бы делать отдельные страницы для брендов, с красивыми url

**Comment by bezumkin** [comment]
У `msVendor` есть поле `resource` для связи со страницей сайта.

**Comment by webinmd** [comment]
> У `msVendor` есть поле `resource` для связи со страницей сайта.

есть.
и если на сайте >100 производителей это делать >100 ресурсов отдельно, вместо того чтобы добавить 1 поле, по которому можно и url красиво сделать и нужный бренд найти

**Comment by bezumkin** [comment]
И url будет генерироваться по хз каким правилам, а виртуальная страница отсутствовать в `robots.txt`. 

А потом понадобится добавить бренду еще список офисов в разных странах, фотогалерею, еще каку-нибудь байду, и каждый раз это нужно будет пихать в админку ms2.

Может, всё-таки, для вывода страниц сайта использовать страницы сайта? Особо ленивые могут написать плагин для автоматического их создания.
