### ISSUE TITLE
msProducts параметр optionFilters запросы с операторам  OR и т.д

### ISSUE THREAD

**Issue by OlegShchavelev** [modx-pro/miniShop2#415]
## Сообщение об ошибке

При формировании выборки с помощью параметра optionFilters при использовании оператора OR происходит ошибка надо поправить. 

Пример вызова:

```
$products = $modx->runSnippet('msProducts', [
    'parents' => 2,
    'limit' => 100,
    'showLog' => 1,
    'optionFilters' => '{"height:=":"200","OR:height:=":"900"}',
]);
```
Лог ошибки

`0.0002820: Could not process query, error #1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'test '900' AND msProduct.published = 1 AND msProduct.deleted = 0 )  GROU' at line 1`

Обсуждение в группе [MODX Contributors](https://t.me/modx_contributors) начало обсуждения 3 мая 21:38

**Comment by CrazyBoy49z** [comment]
Связанная проблема решали здесь https://modx.pro/help/6700#comment-75967

**Comment by Ibochkarev** [comment]
https://github.com/Ibochkarev/miniShop2/pull/539
