### ISSUE TITLE
Организация чанков в окне настройки Статуса Заказа

### ISSUE THREAD

**Issue by OlegShchavelev** [modx-pro/miniShop2#416]
## Запрос функции

Мне понравилось организация выбора чанка в mvtForms давайте посмотрим на скриншоте. 

![изображение](https://user-images.githubusercontent.com/20732384/81005841-3d4d5a80-8e57-11ea-9826-b6c410d7d732.png)

**Работает по следующему принципу:**

1. Возможно в настройках указать ID категории (modCategory) и тем самым ограничить результаты вывода в селекте.
2. Название чанка в selecte выводится из description тем самым администратор получает более дружелюбную информацию.

Предлагаю данный принцип организовать в разделе **Настройки -> Cтатус заказа**

![изображение](https://user-images.githubusercontent.com/20732384/81006565-6ae6d380-8e58-11ea-9cae-8274cbfe4bfe.png)

**Обратная совместимость**

Данную возможность опциональна. И администратор настраивает ее дополнительно. Возможно как-то сделать по-другому, но этот один из путей.

**Comment by GulomovCreative** [comment]
Отличная идея, да и обратной совместимости тут не надо, по сути ничего не меняется
