### ISSUE TITLE
Убрать картинку MS2 в админке если в галерее ничего не загружено

### ISSUE THREAD

**Issue by frost-agb** [modx-pro/miniShop2#418]
## Запрос функции
![image](https://user-images.githubusercontent.com/22435316/81283379-942c7d00-906d-11ea-8a68-7a4c63737ab5.png)

Хотелось бы убрать данную картинку, если в галерее ничего не загружено

### Зачем это нужно?

Если создавать каталог на основе minishop2 и в этом каталоге нет картинок, например просто список фирм, то в админке эта картинка не нужна и смотрится лишней.

**Comment by Ruslan-Aleev** [comment]
Наверное, стоит настройку сделать, так будет универсальнее. При этом нужно будет и продумать вывод (тоже как-то отключить) в сетке товаров.

**Comment by frost-agb** [comment]
> Наверное, стоит настройку сделать, так будет универсальнее. При этом нужно будет и продумать вывод (тоже как-то отключить) в сетке товаров.

в сетке можно отключить в настройках, просто thumb убираешь и всё, а вот тут увы нет такого

**Comment by CrazyBoy49z** [comment]
> Наверное, стоит настройку сделать, так будет универсальнее. При этом нужно будет и продумать вывод (тоже как-то отключить) в сетке товаров.

Это будет наилучшим решением, так как убирать если не загружена не логично

**Comment by Ruslan-Aleev** [comment]
> > Наверное, стоит настройку сделать, так будет универсальнее. При этом нужно будет и продумать вывод (тоже как-то отключить) в сетке товаров.
> 
> Это будет наилучшим решением, так как убирать если не загружена не логично

В принципе, можно сделать проверку на пустоту, типа если есть картинка - выводится, если нет, то нет. **Без настройки**. Просто наблюдать лого - не особо полезно :)
Но там придется условие писать за сеткой элементов, т.к. еще меняется и ширина поля (columnWidth) - https://github.com/bezumkin/miniShop2/blob/master/assets/components/minishop2/js/mgr/product/product.common.js#L117

**Comment by CrazyBoy49z** [comment]
> > > Наверное, стоит настройку сделать, так будет универсальнее. При этом нужно будет и продумать вывод (тоже как-то отключить) в сетке товаров.
> > 
> > 
> > Это будет наилучшим решением, так как убирать если не загружена не логично
> 
> В принципе, можно сделать проверку на пустоту, типа если есть картинка - выводится, если нет, то нет. **Без настройки**. Просто наблюдать лого - не особо полезно :)
> Но там придется условие писать за сеткой элементов, т.к. еще меняется и ширина поля (columnWidth) - https://github.com/bezumkin/miniShop2/blob/master/assets/components/minishop2/js/mgr/product/product.common.js#L117

+ добавить настройку, чтобы отображалась чтобы клиенту не объяснять

**Comment by Ruslan-Aleev** [comment]
> добавить настройку, чтобы отображалась чтобы клиенту не объяснять

А зачем вообще настройка? Как она работать-то должна в итоге?

Я для себя пока не понял. miniShop2 используется для каталога, но там большой плюс - галерея. Если есть фото - выводится фото, если нет - ничего не выводится. Если делать настройку для превью в общем, то можно отключить отображение превью из галереи, что не полезно. А если делать настройку только для отключения лого, то это излишняя настройка.

**Comment by CrazyBoy49z** [comment]
> > добавить настройку, чтобы отображалась чтобы клиенту не объяснять
> 
> А зачем вообще настройка? Как она работать-то должна в итоге?
> 
> Я для себя пока не понял. miniShop2 используется для каталога, но там большой плюс - галерея. Если есть фото - выводится фото, если нет - ничего не выводится. Если делать настройку для превью в общем, то можно отключить отображение превью из галереи, что не полезно. А если делать настройку только для отключения лого, то это излишняя настройка.

Как подсказка клиенту если заполняет товар что можно ещё картинки добавлять

**Comment by Ibochkarev** [comment]
Я для клиентов загружаю фото заглушку по тематике продукции:
![image](https://user-images.githubusercontent.com/2138260/85201897-951b2480-b324-11ea-8600-5b282a9dd9d6.png)
