### ISSUE TITLE
При клике на таб не рендерится в grid доступ запрещен

### ISSUE THREAD

**Issue by OlegShchavelev** [modx-pro/miniShop2#423]
Если к примеру ограничить параметр mssetting_list в политике доступы. Мы увидим небольшой баг при клике на таб. Прикладываю скриншот настройки. 

![изображение](https://user-images.githubusercontent.com/20732384/81743312-1f60a500-94aa-11ea-90ed-6a5402ca46e4.png)

Скринкаст не исправности

![politic_setting](https://user-images.githubusercontent.com/20732384/81743691-bf1e3300-94aa-11ea-88f0-165f554c0873.gif)

### Среда

Версия miniShop2 2.5.1 (Версия GitHub), версия MODX 2.7.3

**Comment by GulomovCreative** [comment]
Не совсем понимаю, а в чем баг?

**Comment by GulomovCreative** [comment]
Варианты доставки, Способы оплаты и т.д. все еще являются настройками магазина и при отключении права доступа mssetting_list они как раз и перестают выводится. А как должно быть?

**Comment by webinmd** [comment]
> Варианты доставки, Способы оплаты и т.д. все еще являются настройками магазина и при отключении права доступа mssetting_list они как раз и перестают выводится. А как должно быть?

видимо речь о том что надпись Доступ запрещен появляется только при обновлении страницы, а если кликать по табам, то нет надписи никакой

**Comment by GulomovCreative** [comment]
> видимо речь о том что надпись Доступ запрещен появляется только при обновлении страницы, а если кликать по табам, то нет надписи никакой

Это "баг" самого MODX, ну или скорее всего ExtJS
