### ISSUE TITLE
Выводить вкладку "Галерея" в товаре всегда, но с разъяснением

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modx-pro/miniShop2#426]
### Резюме
При создании товара вкладка "Галерея" изначально отсутствует т.к. еще нет ID ресурса и Галерея не знает куда загружать файлы.
Однако это не понятно для конечного пользователя, очень часто менеджеры спрашивают "куда загружать картинки, нет вкладки галереи, галерея пропала" и т.п.

![product-gallery](https://user-images.githubusercontent.com/12523676/82194653-d40e2280-98ff-11ea-8da2-601b1ad1f8cc.gif)

**Думаю, вкладка должна быть всегда, но если ресурс еще не сохранен, то должно быть текст-разъяснение во вкладке или всплывашка.**

### Зачем это нужно?
Думаю, вкладка должна быть всегда, для UI/UX, чтобы снять вопросы менеджеров.

### Предлагаемое решение(я)
Вкладка должна быть всегда, но если ресурс еще не сохранен, то должно быть текст-разъяснение во вкладке или всплывашка, типа:

```
Галерея изображений не активна, т.к. ресурс ещё не создан в базе данных.
Пожалуйста, сохраните ресурс для загрузки изображений в галерею.
```

### Связанные проблема(ы)/PR(ы)
Нет

**Comment by webinmd** [comment]
Да, тоже часто получаю вопросы по поводу отсутствия галереи
