### ISSUE TITLE
Добавить ссылку на системные настройки в меню пакета miniShop2

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modx-pro/miniShop2#429]
### Резюме
Оказывается, можно ссылаться на системные настройки конкретного пакета по ссылке:
`/manager/?a=system/settings&ns=minishop2`
Я предлагаю добавить такую ссылку в верхнее меню пакета, например:

![ms_sys_settings](https://user-images.githubusercontent.com/12523676/83496604-043def80-a4c2-11ea-8a83-10d31bb04592.png)

Почему это мало кто делает - не ясно.
**Хотя тут нужно продумать контроль доступа, как минимум, скрыть для не админа.**

### Зачем это нужно?
Во-первых, полезно для UX - меньше кликов.
Во-вторых, для новичков будет понятнее как и что настраивается и где искать настройки.

### Предлагаемое решение(я)
Предлагаю добавить ссылку 
`/manager/?a=system/settings&ns=minishop2` в верхнее меню пакета.

_p.s. И странно, что ссылка рабочая ссылка не вида `&namespace=minishop2`, а `&ns=minishop2`._

### Связанные проблема(ы)/PR(ы)
Нет

**Comment by Ibochkarev** [comment]
Added #430
