### ISSUE TITLE
Кнопки "Быстро создать категорию\товар"

### ISSUE THREAD

**Issue by meshkov** [modx-pro/miniShop2#437]
## Сообщение об ошибке
При нажатии кнопки Быстро создать -> Категория товаров или Быстро создать -> Товар магазина - открывается обычное создание ресурса.

### Ожидаемое поведение
Должно подтягиваться все.
Например при быстром создании категории даже не подтягивается нужный шаблон. Про товар вообще не говорю)
Если конечно это не возможно исправить, то может есть возможность убрать эти кнопки быстрого создания? Эти кнопки сбивают очень при работе с магазином.

### Среда

miniShop2 2.5, версия MODX 2.7.3.

**Comment by meshkov** [comment]
Думаю это связанные проблемы - https://github.com/bezumkin/miniShop2/issues/82

**Comment by GulomovCreative** [comment]
> Думаю это связанные проблемы - #82

Спасибо, связал с #439, эта проблема решена в нем
