### ISSUE TITLE
Добавить микроразметку

### ISSUE THREAD

**Issue by Ibochkarev** [modx-pro/miniShop2#442]
### Резюме

Добавить микроразметку [schema.org](https://schema.org/) в чанки

### Зачем это нужно?

Микроразметка карточки товара позволит поисковым роботам понять, где указана цена на товар, где представлено его описание, а где – фотография. И так далее

### Предлагаемое решение(я)

Подготовить PR

### Связанные проблема(ы)/PR(ы)

NA.

**Comment by webinmd** [comment]
тут может возникнуть проблема у фанатов json ld. 
Хотя я никогда не использовал родные чанки

**Comment by Ibochkarev** [comment]
> тут может возникнуть проблема у фанатов json ld.
> Хотя я никогда не использовал родные чанки

Добавить пример в документацию.
