### ISSUE TITLE
Переписать чанки на Fenom

### ISSUE THREAD

**Issue by Ibochkarev** [modx-pro/miniShop2#443]
### Резюме

Переписать содержимое чанков на Fenom

### Зачем это нужно?

Для современного вектора разработки магазинов с использованием Fenom

### Предлагаемое решение(я)

Подготовить PR

### Связанные проблема(ы)/PR(ы)

NA

**Comment by CrazyBoy49z** [comment]
Вань, за какие чанки ещё переписать нашёл только 1, завтра планирую заняться


https://github.com/bezumkin/miniShop2/blob/master/core/components/minishop2/elements/chunks/chunk.ms_product_content.tpl

**Comment by Ruslan-Aleev** [comment]
Ребята, лично я против переписывания на Fenom. MODX работает на своем шаблонизаторе, зачем насильно пихать Fenom всюду?
Для галереи еще понятно - чтоб отдельный сниппет не писать, но тут...
Зарубежные ребята, кстати, не часто Fenom используют.
Особенно криво будет смотреться, когда у тебя другие чанки на MODX-тегах, а чанки miniShop на Fenom.

**Comment by webinmd** [comment]
> Ребята, лично я против переписывания на Fenom. MODX работает на своем шаблонизаторе, зачем насильно пихать Fenom всюду?

Ну тут чанки и так уже в большинстве на fenom

**Comment by Ruslan-Aleev** [comment]
> Ну тут чанки и так уже в большинстве на fenom

Да, странно, думал, что наоборот. Тогда вопрос снят.

**Comment by Ibochkarev** [comment]
Добавлено в #478
