### ISSUE TITLE
Добавить сумму для бесплатной доставки

### ISSUE THREAD

**Issue by webinmd** [modx-pro/miniShop2#446]
### Резюме

Добавить поле для указания суммы, после которой доставка будет бесплатной

### Зачем это нужно?

Частый запрос такого функционала

### Предлагаемое решение(я)

Добавить в окно создания/редактирования доставки поле для указания суммы

![2020-07-01_11-56-52](https://user-images.githubusercontent.com/966234/86224830-0ca54b00-bb92-11ea-9668-39d825de852a.png)

**Comment by Ibochkarev** [comment]
![image](https://user-images.githubusercontent.com/2138260/86227121-6a479080-bbae-11ea-9722-76b328c0c832.png)

**Comment by Electrica** [comment]
Да вроде легко решается расширением класса заказа. Но да, возможно было бы удобнее

**Comment by OlegShchavelev** [comment]
Да замечательная идея.

**Comment by webinmd** [comment]
взял в работу
