### ISSUE TITLE
Пути в медиа-источнике некорректно ставятся при установке miniShop2, если папка assets/ переименована

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modx-pro/miniShop2#454]
### Резюме
Если папка `assets/` переименована, то пути в медиа-источнике некорректно ставятся **при установке miniShop2**.

На одном проекте папка `assets/` была переименована, например, в `cstAssets/` и в медиа-источнике MS2 Images настройка `basePath` при установке miniShop2 задалась автоматически (с новым путем cstAssets/), а в `baseUrl` остался старый путь (с assets/).

### Наблюдаемое поведение
Некорректные пути в конфигах медиа-источника.

### Ожидаемое поведение
Все конфиги медиа-источника должны цеплять новый путь к assets.

### Среда
miniShop2 2.5, MODX 2.7.3

**Comment by CrazyBoy49z** [comment]
@Ruslan-Aleev нужно протестировать

**Comment by Ibochkarev** [comment]
Fixed #489
