### ISSUE TITLE
Изменить порядок вкладок для категории

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modx-pro/miniShop2#456]
### Резюме
В нынешнем варианте miniShop2 у категории используемые вкладки разделены редко используемыми, например, вкладка "TV", "Настройки", еще и вкладка "Комментариев", если tickets установлен.

### Зачем это нужно?
Было бы полезным изменить порядок вкладок по частоте использования - станет полезнее для UX.
То же, что и https://github.com/bezumkin/miniShop2/issues/367 , но для "Категории".

p.s. Когда правили вкладки товара, как-то про категорию забыли :)

### Связанные проблема(ы)/PR(ы)
https://github.com/bezumkin/miniShop2/pull/376
https://github.com/bezumkin/miniShop2/issues/367

**Comment by Ibochkarev** [comment]
Исправлено в #459
