### ISSUE TITLE
Защита от спам-заказов 

### ISSUE THREAD

**Issue by kullout** [modx-pro/miniShop2#463]
Столкнулся со спамерами , которые со скриптам автокликеров, с фронта делают фейковые заказы. 
И за ночь таких заказов может выйти 300-400.

### Зачем это нужно?
Запретить осуществлять заказы если в базе имеется определённое количество с одним статусом

### Предлагаемое решение(я)

Можно поставить на событие onBeforeCreateOrder проверку и если есть от такого юзера (user_id) заказ (ну или 2 заказа, выставить значение в системных настройках) в статусе (status = 1) "новый", то не добавлять заказ в базу,  а отправлять на другую страницу сайта "дождитесь завершения предыдущего заказа " к примеру
### Связанные проблема(ы)/PR(ы)
И также внедрить проверку при оформлении заказа на наличие заказа в корзине, как описано тут:
https://modx.pro/development/20562#comment-122156
Чтобы предотвратить с фронта отправлять пустые заказы

**Comment by mattersj** [comment]
>то не добавлять заказ в базу, а отправлять на другую страницу сайта "дождитесь завершения предыдущего заказа "

Такое никто не будет делать. Добавь обычную капчу или скрытое поле для отсечения ботов.

**Comment by kullout** [comment]
> > то не добавлять заказ в базу, а отправлять на другую страницу сайта "дождитесь завершения предыдущего заказа "
> 
> Такое никто не будет делать. Добавь обычную капчу или скрытое поле для отсечения ботов.

В том то и дело, что капча есть и скрытая кнопка есть, ботов не пускает, амвот именно автокликеры,  по скрипку имитируя поведение человека, осуществляется множество заказов. 
Неужели это такая сложная в реализации система ?

**Comment by mattersj** [comment]
>Неужели это такая сложная в реализации система ?

В том то и дело, что нет. Но это нишевая фича, которую будут юзать 1.5 человека, поэтому ты должен реализовать ее самостоятельно. Дело 5-10 минут, ты уже даже сам предложил решение.

**Comment by kullout** [comment]
> > Неужели это такая сложная в реализации система ?
> 
> В том то и дело, что нет. Но это нишевая фича, которую будут юзать 1.5 человека, поэтому ты должен реализовать ее самостоятельно. Дело 5-10 минут, ты уже даже сам предложил решение.

Вот предложили решение ребята в телеграмм канале сообщество модх. Как эту казалось бы простую задачу, но я сам не в силах решить.
И по поводу 1.5 человека, я не согласен.
Это плюс в общую копилку безопасности модх и в частности именно минишоп2. 
Так как повторюсь, даже капча и скрытое поле для ботов, не может запретить спамить базу заказами через автокликеры. А если у меня настроен не мейл отправка заказов пользователю, а смс, то за каждый пустой заказ, я с кармана отдаю 0.4 гривны.
Это почти 1 рубль. Вот 300 спам заказов, минус 300 рублей.... 

Я даже готов спонсировать написание, много нету, но 600 гривен,  10% от моей месячной зарплаты я могу выделить, если будет написано в обновлении, или же отдельным дополнением к минишоп2.

**Comment by kullout** [comment]
600 гривен (1620 рублей некоторые более существенные дополнения стоят на портале модсторе.про дешевле)
Есть,  кто может потратить 5-10 минут? Человек который разбирается в этом,  и сможет реализовать требуемое грамотно и правильно. Стоит оно этих денег?

**Comment by mattersj** [comment]
>Это плюс в общую копилку безопасности модх

Это не имеет ничего общего с безопасностью.

>А если у меня настроен не мейл отправка заказов пользователю, а смс, то за каждый пустой заказ, я с кармана отдаю 0.4 гривны.

Опять же, это нужно далеко не всем и это довольно специфичная фича, поэтому ее никто не будет реализовывать из коробки.
Гораздо проще и правильнее [нанять разработчика](https://modx.pro/work), который сделает это лично тебе, на твоем сайте.
