### ISSUE TITLE
Сменить цвет для кнопок навигации в сетке

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modx-pro/miniShop2#464]
### Резюме
Кнопки навигации в сетке, а именно, "Включить" / "Выключить" почти не отличаются визуально, что путает.

![on-off](https://user-images.githubusercontent.com/12523676/97552362-386ffa80-19e5-11eb-8c1e-15be2f1f3ce6.png)

Нужно поменять цвет или фон у кнопок, дабы пользователи не путались.

Также **имеет смысл добавить прозрачность и картинкам и кнопкам управления** (т.к. глаз цепляет картинку, и кажется что строка активна):

```
.minishop2-row-inactive .x-grid3-col-image img {
    opacity: .5;
}

.minishop2-row-inactive ul.minishop2-row-actions {
    opacity: .5;
}
```

Как вариант (сменил цвет, добавил прозрачность):

![on-off-2](https://user-images.githubusercontent.com/12523676/97553745-e039f800-19e6-11eb-93fe-2a8f40da4e00.png)

### Зачем это нужно?
Улучшение UI/UX

### Связанные проблема(ы)/PR(ы)
Нет

**Comment by Ibochkarev** [comment]
**Или типо этого:**

![Снимок экрана 2020-10-29 в 16 52 37](https://user-images.githubusercontent.com/2138260/97559122-3a4ab580-1a07-11eb-8669-6ab23f5a5d4e.png)

**Comment by webinmd** [comment]
> **Или типо этого:**
> 


перебор

**Comment by Ruslan-Aleev** [comment]
> **Или типо этого:**
> 

Я думал об этом варианте, но сейчас кнопки в глаза сильно бросаются :)

**Comment by Ruslan-Aleev** [comment]
Там нужно у кнопки выключения сменить `.action-gray` на `.action-red`, поменять цвета у `.action-red` и `.action-green` (сделать их поярче), и добавить прозрачность к кнопкам управления и картинки, если строка вся выключена (`.minishop2-row-inactive`).
