### ISSUE TITLE
Ошибка с датами в админке (2.6.0)

### ISSUE THREAD

**Issue by rpadesign** [modx-pro/miniShop2#474]
## Сообщение об ошибке
В консоли ошибка, что не существует функция strftime:
`
Uncaught TypeError: date.strftime is not a function
    at constructor.miniShop2.utils.formatDate [as renderer] (ms2.utils.js:12)
    // ..............
`

### Шаг для воспроизведения
Например, в msDiscount (он использует ms2.utils.js) все виснет при рендеринге грида.

### Причина
В новом assets/components/minishop2/js/mgr/misc/ms2.utils.js отсутствует подключение strftime-min-1.3.js как оно было ранее:
`
Ext.Loader.load([
    MODx.config.assets_url + 'components/minishop2/js/mgr/misc/strftime-min-1.3.js'
]);
`

**Comment by Ibochkarev** [comment]
@ilyautkin посмотри плиз

**Comment by webinmd** [comment]
В msDiscount были внесены изменения, в msPromoCode2 проблема не наблюдается
