### ISSUE TITLE
На странице заказа (Админка) не отображается данные поля receiver

### ISSUE THREAD

**Issue by OlegShchavelev** [modx-pro/miniShop2#477]
### Резюме

Если вставить в системную настройку ms2_order_grid_fields поле receiver, то данные в админке не будут отображаться. Как по прошлым заказам которые были совершены, так и по новом заказам.

Скриншот

![изображение](https://user-images.githubusercontent.com/20732384/99142036-41f29700-2662-11eb-9e20-4fd659b408d6.png)
 
### Шаг для воспроизведения

В системных настройках  ms2_order_grid_fields добавить поле receiver

### Ожидаемое поведение

При добавлении в настройку ms2_order_grid_fields поле receiver, данные должны поступать.

### Среда

Версия miniShop2, 2.5.0, 2.6.0 Minishop 2.8.1 

Cпасибо.

**Comment by Ibochkarev** [comment]
Данные берутся с таблицы `ms2_orders`, а там такого поля просто нет

![image](https://user-images.githubusercontent.com/2138260/99142613-e2f04a80-2680-11eb-9393-99d9541d789c.png)

**Comment by OlegShchavelev** [comment]
Да все правильно ты написал. Если брать из неудобств, то на текущий момент если в форме заказа нет почты (поле email), то в заказе поле customers будет fakeData (почта) и так же если внедрен Office, то пользователь может изменить имя пользователя и при определенных настройках администратор не будет видеть Имя и Фамилию покупателя. В других случаях данные будут аналогично receiver 

Ну это мои фантазии на тему если я бы это написал, что я мог иметь ввиду!

**Comment by webinmd** [comment]
Не очень понимаю необходимость этого. При создании заказа создаётся пользователь, у которого и прописывается Имя. То есть по факту имя receiver всегда является  именем пользователя.

**Comment by OlegShchavelev** [comment]
Я написал выше в каких случаях это не так. Плюс это вопрос с modx.pro а не мой. Хотя в большинстве случаях @webinmd прав, но есть исключение. Поэтому я предлагаю не писать что и так очевидно, а вот к примеру поговорить об исключениях.

https://modx.pro/help/21073 - вот ссылка на статью.
