### ISSUE TITLE
Не хватает перевода для системных настроек ms2_add_icon_category и ms2_add_icon_product

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modx-pro/miniShop2#493]
### Резюме
По-моему, не хватает перевода для системных настроек `ms2_add_icon_category` и `ms2_add_icon_product`:

![ms_ss](https://user-images.githubusercontent.com/12523676/100912768-f5bca900-34e1-11eb-9db2-c096440b601f.png)

### Среда
miniShop2 2.6.0

**Comment by webinmd** [comment]
а также для ms2_chunks_categories

**Comment by Ibochkarev** [comment]
Добавлено в #495
