### ISSUE TITLE
"return json" в сниппете msProducts

### ISSUE THREAD

**Issue by mngatoff** [modx-pro/miniShop2#499]
### Резюме

Сниппет pdoResources имеет параметр return, который позволяет выводить данные в нужном формате. Сниппет msProducts, который по идее должен быть просто надстройкой над pdoResources, поддерживает только два из этих форматов - id и чанки.

### Зачем это нужно?

Часто бывает нужна небольшая выборка товаров. Или выборка, которую можно запросить один раз, а потом разделить по нескольким блокам в верстке. В таких случаях очень нужен "return json". Кроме того, это позволяет вообще не создавать лишние чанки, где в них нет необходимости, а формировать верстку товаров прямо в цикле. На данный момент для этого приходится кастовать собственный сниппет, в который скопирован весь код из msProducts и изменены две строчки. Это нерационально. Как и нерационально в сниппете-обертке делать даунгрейд возможностей основного сниппета :)

### Предлагаемое решение

На строке 210 в сниппете msProducts происходит добавление данных в выходной массив. На этом этапе нужно сделать проверку параметра return и обработать данные в зависимости от него. В конце сниппета тоже нужно сделать проверку и выводить либо $output, либо json_encode($output)

### UPD.
Еще на строке 233 создается принудительный outputSeparator, можно его тоже выпилить? он там непонятно зачем и попил кровушки в свое время

**Comment by Ibochkarev** [comment]
@gvozdb Сможешь реализовать?
