### ISSUE TITLE
Расширить выпадающий список товаров во вкладке Покупки у заказа

### ISSUE THREAD

**Issue by webinmd** [modx-pro/miniShop2#502]
### Резюме

У заказа во вкладке **Покупки** есть выпадающее поле с поиском товаров, для добавления его к заказу. на данный момент поле занимает около 30% от ширины, хотелось бы его расширить до 100%

### Зачем это нужно?

Я всегда расстраиваюсь, когда наименование товара длиннее данного поля. Могут же быть товары, у которых отличие в названии где-то в конце (например литраж/размер/цвет) и не всегда выбираешь нужный товар

### Предлагаемое решение(я)

Расширить поле до 100%

Сейчас вот так:

![Покупки](https://user-images.githubusercontent.com/966234/101881333-ee119a00-3b9c-11eb-84f2-81b55eb81169.png)

**Comment by Ibochkarev** [comment]
Улучшено в #502
