### ISSUE TITLE
Учет остатков

### ISSUE THREAD

**Issue by bezumkin** [modx-pro/miniShop2#51]
Добавить простой учет остатков, без параметров - как было у MS1.

**Comment by tokezooo** [comment]
Когда планируется реализация?

**Comment by iWatchYouFromAfar** [comment]
В магазине 2 пакета, которые реализуют данный функционал:

https://modstore.pro/packages/ecommerce/msoptionsprice2
https://modstore.pro/packages/ecommerce/msproductremains

Я думаю, что имеет смысл закрыть данный issue.
