### ISSUE TITLE
Included Paypal payment method needs updated certificate bundle

### ISSUE THREAD

**Issue by Jsewill** [modx-pro/miniShop2#514]
## Сообщение об ошибке
.../core/components/minishop2/custom/payment/paypal.class.php : 84) [miniShop2] Payment error while request. Request: Array
(
...
)
, response: Peer certificate cannot be authenticated with known CA certificates

### Резюме

It appears that the peer certificate bundle in the included payment gateway is deprecated. Furthermore, MiniShop2 does not indicate failure when this happens, but creates the order and notifies the relevant parties just the same. I'm sorry that I'm not more familiar with the codebase. If I were, I'd offer a pull request.

### Шаг для воспроизведения

No custom code is necessary, simply attempt to place an order.

### Ожидаемое поведение

There should be no certificate related error. Also, perhaps the order process should be halted on any significant error.

### Среда

MiniShop2 v. 2.7.0-pl, MODX 2.8.1-pl

**Comment by Ibochkarev** [comment]
@Jsewill please try change 
https://github.com/webinmd/miniShop2/blob/1e1f766a72b1dbf0f14c8ef448fa8dc13fc88c28/core/components/minishop2/custom/payment/paypal.class.php#L165

`CURLOPT_SSL_VERIFYPEER, false`

**Comment by Jsewill** [comment]
I actually just went ahead and bundled the proper certificates:

DigiCertGlobalRootG2.crt.pem
DigiCertHighAssuranceEVRootCA.crt.pem
api-3t.paypal.com.pem

into cabundle.pem, and updated the paypal.php file accordingly.

That seemed to take care of the problem for me, now I'm getting a different error, but that's probably just related to the paypal account I'm using.

**Comment by Jsewill** [comment]
For further reference:

https://www.paypal.com/us/smarthelp/article/migration-to-digicert-root-certificates-ts2240
https://www.paypal.com/us/smarthelp/article/ts1510
https://www.digicert.com/kb/digicert-root-certificates.htm

**Comment by webinmd** [comment]
best solution would be to write a separate component and remove it from minishop core

**Comment by biz87** [comment]
Вроде решен вопрос? @Ibochkarev

**Comment by Ibochkarev** [comment]
Fixed #573
