### ISSUE TITLE
Free delivery field on delivery method seems to do nothing.

### ISSUE THREAD

**Issue by Jsewill** [modx-pro/miniShop2#516]
## Сообщение об ошибке

None.

### Резюме

Free delivery amount doesn't seem to affect the total cost at order placement, and during the payment process.

### Шаг для воспроизведения

MiniShop2->Settings->Deliveries->Update, set the free delivery amount to any positive value. On the frontend, add items to cart until that value has been reached or exceeded. Take note of the total cost of the order.

### Наблюдаемое поведение

While a cursory review of `minishop2/model/minishop2/msdeliveryhandler.class.php` seems to show that it accounts for free delivery, this is not affecting the frontend, or the submitted order.

### Ожидаемое поведение

The total cost of the order should reflect a zero delivery cost.

### Среда

MiniShop2 v. 2.7.0-pl, MODX 2.8.1-pl

**Comment by Ibochkarev** [comment]
@Jsewill please check error log and the presence of the `free_delivery_amount` field in the `modx_ms2_deliveries` table
![image](https://user-images.githubusercontent.com/2138260/102808858-36298b80-43eb-11eb-88f8-e32534b9f8d7.png)

**Comment by Jsewill** [comment]
The MODX error log has `core/cache/includes/elements/modsnippet/13.include.cache.php : 98) PHP warning: Invalid argument supplied for foreach()` where 13 is msProducts. I suspect that is unrelated.

No PHP errors.

The `free_delivery_amount` column is present, and its value correct in the appropriate row.

**Comment by webinmd** [comment]
In miniShop 2.8.1 I cannt reproduce this error
