### ISSUE TITLE
Рассмотреть вопрос удаления из дистрибутива каталога mysql

### ISSUE THREAD

**Issue by biz87** [modx-pro/miniShop2#521]
Каталог mysql генерируется автоматически на основе XML карты компонента и в работе дистрибутива не используется. 
Необходимо протестировать установку при его отсутствии. 

Зачем это нужно:

1.  Лишний неиспользуемый код
2.  При добавлении нового поля - люди начинают заполнять еще и классы внутри каталог mysql.  Лишняя бесполезная работа
3. Есть шанс что эти данные просто копируются и при неверном заполнении могут сломать работу компонента. 
4. Лучше придерживаться принципа единого источника

**Comment by alroniks** [comment]
Ты имеешь ввиду каталог внутри `model`? Если так, то эта штука нужна, потому что по ней MODX ищет необходимые реализации классов. Так получилось, что в minishop2 только mysql поддерживается, но чтобы завести его на postgress, например, то нужно генерировать такую же папку для pgsql и тд. И они должны быть для правильной работы.

**Comment by biz87** [comment]
Я понимаю зачем в установленном компоненте этот каталог.  Но насколько я понимаю каталог генерируется автоматически на основе XML карты моделей.  И зачем этот каталог именно в дистрибутиве мне не понятно пока что. 
Справедливости ради я не не смотрел используется ли он вообще при установке минишопа.

**Comment by alroniks** [comment]
При установке не нужен, но нужен для работы. Код моделей по схеме собирается не во время установки, а разово, потом уже кладется в пакет.
