### ISSUE TITLE
Улучшить страницу оформления заказа добавив новые поля

### ISSUE THREAD

**Issue by alroniks** [modx-pro/miniShop2#524]
### Резюме / Summary

При заказе товаров с доставкой в больших городах часто очень актуальным становится номер подъезда и этаж, где расположена квартира. Так же бывает пишут код от подъезда, но не везде. Можно в комментарий добавлять.

### Зачем это нужно / Why is it needed?

Эту информацию удобно печатать курьеру, чтобы он был в курсе и лишний раз не звонил и не уточнял.

### Предлагаемое решение(я) / Proposed solution (s)

Добавить поля Этаж и Подъезд в форму оформления заказа. Добавить их так же в дефолные чанки. Удалить всегда проще, чем добавить. Кому не нужно, просто вычеркнут.

### Связанные проблема(ы)/PR(ы) / Associated problem (s) / PR (s)

N/A

**Comment by Electrica** [comment]
Вообще было бы круто, если бы поля просто можно было бы создавать.
