### ISSUE TITLE
Не генерируются превью при добавление фото к товарам

### ISSUE THREAD

**Issue by Ibochkarev** [modx-pro/miniShop2#526]
### Резюме / Summary

Не генерируется главное превью при добавление фото к товарам. Ошибка появилась после обновления с версии 2.6.0 до 2.7.0

### Шаг для воспроизведения / Step to play

Создать товар и добавить фото

### Наблюдаемое поведение / Observed behavior

![Снимок экрана 2021-01-16 в 15 58 01](https://user-images.githubusercontent.com/2138260/104808939-ae7d4400-5813-11eb-8441-365360f42d63.png)

![Снимок экрана 2021-01-16 в 15 57 10](https://user-images.githubusercontent.com/2138260/104808941-b0470780-5813-11eb-956e-d5ab35d589ef.png)

В журнале ошибок:

``` php
16.01.2021	12:50:45	WARN	/var/www/topplant/data/www/topplant.ru/core/components/minishop2/processors/mgr/gallery/generate.class.php	45
PHP notice: Undefined index: url
```

### Ожидаемое поведение / Expected behavior

Должно генерироваться превью

### Environment

Версия miniShop2 2.7.0, версия MODX 2.8.1, php 7.4.3

**Comment by Ibochkarev** [comment]
Связано с https://modx.pro/components/21212#comment-125968

**Comment by Ibochkarev** [comment]
https://modx.pro/components/21212#comment-126040

**Comment by CrazyBoy49z** [comment]
Тут скорее нужно исправлять поддержку, но скорее проблема кроется в MODX

**Comment by Ibochkarev** [comment]
> Тут скорее нужно исправлять поддержку, но скорее проблема кроется в MODX

Так и есть. По Mysql 8 висят issue уже давно
