### ISSUE TITLE
Ошибка создания доставки с пустым полем free_delivery_amount

### ISSUE THREAD

**Issue by Electrica** [modx-pro/miniShop2#530]
## Сообщение об ошибке / Error message

![image](https://user-images.githubusercontent.com/3878386/106746230-7156e580-664c-11eb-86d5-d109d159d6ab.png)

INSERT INTO `modx_ms2_deliveries` (`name`, `description`, `price`, `weight_price`, `distance_price`, `logo`, `rank`, `active`, `class`, `requires`, `free_delivery_amount`) VALUES ('Доставка', '', '500', '0', '0', '', 1, 1, '', '', '')
Array
(
    [0] => HY000
    [1] => 1366
    [2] => Incorrect decimal value: '' for column 'free_delivery_amount' at row 1
)

Если не указать поле "Бесплатная доставка от суммы" то не создает и не редактирует доставку. Нужно указывать на пример 0

### Environment

Версия miniShop2 2.8.0, версия MODX 2.8.1, Nginx, Chrome

**Comment by webinmd** [comment]
Не могу воспроизвести баг в версии miniShop2 2.8.1

**Comment by den-dev-icmy** [comment]
А я могу
**ENV:**
php: 8.0.2
modx: 2.8.3
minishop2: 2.9.3
db: Ver 15.1 Distrib 10.6.5-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
**Docker ENV:**
OS (modx): Alpine Linux 3.13.2
OS (db): Ubuntu 20.04.3 LTS
 
<img width="765" alt="Screenshot 2021-12-03 at 11 21 45" src="https://user-images.githubusercontent.com/67893005/144561813-63d9fee1-961b-4ad2-8c6c-f86227286538.png">
<img width="1180" alt="Screenshot 2021-12-03 at 11 21 37" src="https://user-images.githubusercontent.com/67893005/144561825-8c22d5ba-a574-4bbe-923b-76b32c00fd9a.png">
