### ISSUE TITLE
Отказ от старых версий php 

### ISSUE THREAD

**Issue by CrazyBoy49z** [modx-pro/miniShop2#531]
### Резюме / Summary

Отказаться от версий php 5.3, 5.4, 5.5

### Зачем это нужно / Why is it needed?

На дворе 2021 год, и думаю уже поддерживать эти версии не нужно, а уже есть версия 8.0.1. Что не устраивает MODX через поддержку старых версий очень отстает. Так как в минишопе можно было сделать рефакторинг кода или перенести уже в 3?

**Comment by meshkov** [comment]
Конечно стоит отказаться)
В документации [docs.modx.com](https://docs.modx.com/current/en/getting-started/server-requirements) в требованиях:
![image](https://user-images.githubusercontent.com/1703670/107787607-5f69f680-6d60-11eb-8e91-676e0ee2798f.png)

**Comment by alroniks** [comment]
Без нормальной статистики трудно сказать. Тут только если просить Леню как-то собрать ее хотя бы с modxhost, на каких версиях там все работает, в разрезе, где установлен minishop2. И я не знаю, собирает ли modstore статистику по версиям php в момент установки пакета. Но можно попробовать узнать.

**Comment by CrazyBoy49z** [comment]
> Без нормальной статистики трудно сказать. Тут только если просить Леню как-то собрать ее хотя бы с modxhost, на каких версиях там все работает, в разрезе, где установлен minishop2. И я не знаю, собирает ли modstore статистику по версиям php в момент установки пакета. Но можно попробовать узнать.

Здесь соглашусь потому и создал issue c статусом обсуждения

**Comment by CrazyBoy49z** [comment]
Как нашёл в коде Minishop не полностью работает на php 5.3 вопрос удаляем поддержку от него или восстанавливаем поддержку

https://github.com/Ibochkarev/miniShop2/blob/master/core/components/minishop2/processors/mgr/orders/product/get.class.php#L8

https://github.com/Ibochkarev/miniShop2/blob/master/core/components/minishop2/controllers/resource_create.class.php#L65

https://github.com/Ibochkarev/miniShop2/blob/master/core/components/minishop2/controllers/resource_create.class.php#L70

**Comment by biz87** [comment]
Предлагаю пока что придерживаться php 5.6, потому что есть прецеденты обращений, при попытке отказаться от этой версии.  Все что ниже 5.6 удаляем. 
А есть какие то сервисы валидации кода по заданной версии языка?

**Comment by biz87** [comment]
Нашел сочетание PHP_CodeSniffer + PHPCompatibility
https://github.com/PHPCompatibility/PHPCompatibility
Нужно попробовать

**Comment by CrazyBoy49z** [comment]
> Предлагаю пока что придерживаться php 5.6, потому что есть прецеденты обращений, при попытке отказаться от этой версии. Все что ниже 5.6 удаляем.
> А есть какие то сервисы валидации кода по заданной версии языка?

Понял если буду встречать такой код буду обновлять

**Comment by alroniks** [comment]
@biz87 Есть такая штука https://github.com/rectorphp/rector, он умеет даже текущий код приводить к заданной версии языка

**Comment by CrazyBoy49z** [comment]
> @biz87 Есть такая штука https://github.com/rectorphp/rector, он умеет даже текущий код приводить к заданной версии языка

Спасибо интересная штука
