### ISSUE TITLE
Создать класс управления хранилищем корзины

### ISSUE THREAD

**Issue by biz87** [modx-pro/miniShop2#541]
### Резюме / Summary

Предлагаю создать абстрактный класс определяющий где хранить данные корзины и адреса до создания заказа. 
Сейчас это реализовано через сессии, что не всегда удобно. 

По умолчанию сделаем реализацию абстрактного класса также в сессии, но сможем добавить изменение логики, которая позволит сохранять прототип заказа в базе данных или еще где то (например, кэш)

### Зачем это нужно / Why is it needed?

В современном мире часто приходится реализовывать фронт на базе JS фреймворков,  принимать заказ из мобильного приложения или через API из других источников (сторонние маркетплейсы например).  И не всегда удается правильно поднять сессию, чтобы при каждом обращении к API минишопа добавлять изменять уже существующую корзину. 

### Предлагаемое решение(я) / Proposed solution (s)

Сделать так, чтобы методы `ms2->cart->add()`   `ms2->order->add` и им подобные в процессе выполнения смотрели в новый storageHandler где будет написано куда класть данные в сессию или специальную таблицу базы данных. 

storageHandler можно переопределять по своему и управлять хранением временных данных. 

Таким образом можно не привязываться к сессиям, там где это неуместно и пополнять данные корзины\заказа используя идентификатор таблицы

**Comment by biz87** [comment]
Кроме того такая штука позволит еще и брошенные корзины реализовать, попутно, ничего для этого не делая. 
Это крайне востребованный функционал

**Comment by Electrica** [comment]
А вот за такое жирный плюс. В данный момент очень не удобно постоянно работать с сессией, приходится создавать таблчику куда писать хотя бы корзины от пользователей

**Comment by sergant210** [comment]
Если ещё нужны идеи, обращайтесь! ;))

**Comment by biz87** [comment]
> Если ещё нужны идеи, обращайтесь! ;))

Нам бы рук рабочих - чтобы все уже существующие идеи реализовать

**Comment by sergant210** [comment]
> Нам бы рук рабочих - чтобы все уже существующие идеи реализовать

Чукча не читатель, чукча - писатель. ))

Ещё идея - вынести интерфейс минишопа из админки, чтобы обычные менеджеры не лазили в святая святых.  

П.С. Плюс легче найти разрабов для развития и сопровождения. Скоро совсем не останется разработчиков, помнящих ExtJs 3.4.

**Comment by biz87** [comment]
> Ещё идея - вынести интерфейс минишопа из админки, чтобы обычные менеджеры не лазили в святая святых.

Куда вынести?

**Comment by sergant210** [comment]
На фронт. Что-то типа - site.ru/store/manager

P.S. Блин, тут ещё одним Лексусом попахивает ))

**Comment by biz87** [comment]
> На фронт. Что-то типа - site.ru/store/manager

Сомнительно.  Разве что отдельным пакетом.

**Comment by sergant210** [comment]
Конечно, за большое бабло ))

**Comment by biz87** [comment]
У меня даже несколько готовых реализацией есть на VUE и React И дизайн такого ЛК

**Comment by sergant210** [comment]
По теме. Тут есть вопрос как раз про брошенные корзины. Наверно их чистить надо с какой-то периодичностью.

**Comment by Electrica** [comment]
> > На фронт. Что-то типа - site.ru/store/manager
> 
> Сомнительно. Разве что отдельным пакетом.

да я думаю не стоит это того, вложения и выхлоп просто небо и земля.

**Comment by Ibochkarev** [comment]
> У меня даже несколько готовых реализацией есть на VUE и React И дизайн такого ЛК

Дизайн кстати топовый. Все продумано. Если мы о том, что показывал.

**Comment by biz87** [comment]
Реализовано в 3.0.0
