### ISSUE TITLE
Fix 'Unexpected duplicate selector &quot;.x-menu-list .icon&quot;, first used at line 75 (no-duplicate-selectors)' issue in assets\components\minishop2\css\mgr\main.css

### ISSUE THREAD

**Issue by CrazyBoy49z** [modx-pro/miniShop2#551]
[CodeFactor](https://www.codefactor.io/repository/github/ibochkarev/minishop2/overview/master) found an issue: Unexpected duplicate selector &quot;.x-menu-list .icon&quot;, first used at line 75 (no-duplicate-selectors)

It's currently on:
[assets\components\minishop2\css\mgr\main.css:78](https://www.codefactor.io/repository/github/ibochkarev/minishop2/source/master/assets/components/minishop2/css/mgr/main.css#L78)

**Comment by Ibochkarev** [comment]
Fixed #558
