### ISSUE TITLE
Не изменяется цена если использовать чанк msProduct.content.fenom

### ISSUE THREAD

**Issue by webinmd** [modx-pro/miniShop2#556]
### Резюме / Summary

При использовании плагина на событие msOnGetProductFields с внесенными изменениями из PR #555 и чанка msProduct.content.fenom - видно что цена не меняется

### Шаг для воспроизведения / Step to play

1. Заменить в шаблоне чанк msProduct.content на msProduct.content.fenom 
2. Внести измнения из PR #555 
3. проверить изменяется ли цена

### Наблюдаемое поведение / Observed behavior

Цена не изменяется

### Ожидаемое поведение / Expected behavior

Цена должны изменяться

### Environment
miniShop2 2.8.1 , версия MODX 2.8

### Как починить: 

заменить 
`{$_modx->resource.price}
`

на 
`{$price}
`

**Comment by Ibochkarev** [comment]
Fixed #557
