### ISSUE TITLE
Игнорирование заданного контекста корзины в API режиме

### ISSUE THREAD

**Issue by biz87** [modx-pro/miniShop2#569]
### Резюме / Summary

Если я работаю с минишопом в режиме API и задаю контекст отличающийся от того, в котором нахожусь - Системная настройка `ms2_cart_context` в корзине игнорирует заданный контекст автоматически присваивая текущий. 

### Шаг для воспроизведения / Step to play

В консоли внутри админки (контекст mgr - инициализирую другой контекст)

```
$ms2 = $modx->getService('miniShop2');
$ms2->initialize('web');
$ms2->cart->add(62);
$cart = $ms2->cart->get();
echo '<pre>';
print_r($cart);
```

### Наблюдаемое поведение / Observed behavior

Возвращается пустая корзина, так как товар добавляется в mgr контекст

### Ожидаемое поведение / Expected behavior

Должна возвращаться полная корзина, независимо от того в каком контексте я нахожусь, так как я указал конкретный контекст к которому обращаюсь. 

### Environment

ms 2.8.2

**Comment by biz87** [comment]
Вопрос к @Alexij2

**Comment by biz87** [comment]
Подобное поведение повторяется независимо от статуса настройки `ms2_cart_context`
Кроме того в системной настройке установлен статус по умолчанию false, тогда как в коде - дефолтный статус пустота
`$this->modx->getOption('ms2_cart_context', null, '', true)`
Рекомендую в коде также выставить по дефолту false для корректности

**Comment by Alexij2** [comment]
Нужно протестировать. Если уже это сделали - я не против изменений, если они корректные.
