### ISSUE TITLE
Нечитаемый текст в журнале истории заказа из-за цвета

### ISSUE THREAD

**Issue by Semdevmaster** [modx-pro/miniShop2#571]
## Сообщение об ошибке / Error message
У статусов есть возможность выбирать цвета, и эти цвета используются в сетке заказов как фоновый цвет - это удобно и тут всё хорошо. Но стоит зайти в любой заказ, в его историю и там статусы уже используют эти цвета не фоном, а в самом тексте, что может крайне сложно читаться на белом фоне.

Пример:
![image](https://user-images.githubusercontent.com/2706508/113555643-ecfcf080-9603-11eb-96e5-6623dc8c9528.png)

Версия miniShop2 - 2.8.3

**Comment by Ruslan-Aleev** [comment]
Связано с https://github.com/Ibochkarev/miniShop2/pull/432
