### ISSUE TITLE
Ошибка создания таблицы ms2_options при установке minishop2

### ISSUE THREAD

**Issue by white-vigvam** [modx-pro/miniShop2#572]
## Сообщение об ошибке / Error message
```
Could not create table `ms2_options`
SQL: CREATE TABLE `ms2_options` (`id` INTEGER unsigned NOT NULL AUTO_INCREMENT, `key` VARCHAR(255) NOT NULL DEFAULT '', `caption` VARCHAR(255) NOT NULL DEFAULT '', `description` TEXT NULL, `measure_unit` TINYTEXT NULL, `category` INT(10) unsigned NOT NULL, `type` VARCHAR(255) NOT NULL DEFAULT '', `properties` TEXT NULL, PRIMARY KEY (`id`), INDEX `key` (`type`), FULLTEXT `caption_ft` (`caption`), INDEX `category` (`category`)) ENGINE=InnoDB
ERROR: Array
(
    [0] => HY000
    [1] => 1709
    [2] => Index column size too large. The maximum column size is 767 bytes.
)
```

### Резюме / Summary

Краткое резюме о чем эта проблема. / A short summary of what this problem is about.

### Шаг для воспроизведения / Step to play
При установке modx выбрать тип кодировки таблиц utf8mb4_general_ci
Установить minishop2 от поставщика modx.pro
В модальном окне увидеть ошибку, текст которой указан выше

### Наблюдаемое поведение / Observed behavior

Minishop2 работает до тех пор, пока не нужно воспользоваться опциями.
Попытка создать опцию приводит к ошибке
```
[2021-04-05 20:19:00] (ERROR @ /pathl/core/xpdo/om/xpdoobject.class.php : 1452) Error 42S02 executing statement:
INSERT INTO `ms2_options` (`key`, `caption`, `description`, `measure_unit`, `category`, `type`) VALUES ('test', 'test', '', '', 0, 'textfield')
Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'ms2_options' doesn't exist
)
```

### Environment
minishop2 - 2.8.3
php - 7.1
mysql - 5.6
apache

**Comment by webinmd** [comment]
поменяйте кодировку на **utf8_general_ci**

**Comment by white-vigvam** [comment]
Как решить проблему, я знаю.  Иван Бочкарев попросил написать сюду, чтобы не потерялось. Суть проблемы то в том, что modx в целом и minishop в частности по умолчанию предлагает mb4
Вот первый комментарий Василия в этой посте тому в доказательство.
https://modx.pro/development/20562
И получается что это bug, потому что выбрав предложенную modx кодировку пользователь получает сбой при установке minishop/

**Comment by CrazyBoy49z** [comment]
Как подозреваю установлено innoDB. Исправить можно установив размер строки 191. Только на колонку в которой задан ключ

**Comment by Ibochkarev** [comment]
> Как подозреваю установлено innoDB. Исправить можно установив размер строки 191. Только на колонку в которой задан ключ

https://github.com/Ibochkarev/miniShop2/blob/6aa7562489eac8dea3900e3f41fcf5f45104a4a8/core/components/minishop2/model/schema/minishop2.mysql.schema.xml#L122-L124

**Comment by CrazyBoy49z** [comment]
> > Как подозреваю установлено innoDB. Исправить можно установив размер строки 191. Только на колонку в которой задан ключ
> 
> https://github.com/Ibochkarev/miniShop2/blob/6aa7562489eac8dea3900e3f41fcf5f45104a4a8/core/components/minishop2/model/schema/minishop2.mysql.schema.xml#L122-L124

https://github.com/Ibochkarev/miniShop2/blob/6aa7562489eac8dea3900e3f41fcf5f45104a4a8/core/components/minishop2/model/schema/minishop2.mysql.schema.xml#L447

https://github.com/Ibochkarev/miniShop2/blob/6aa7562489eac8dea3900e3f41fcf5f45104a4a8/core/components/minishop2/model/schema/minishop2.mysql.schema.xml#L453

**Comment by Ibochkarev** [comment]
@CrazyBoy49z  что тут поправить нужно?)

**Comment by CrazyBoy49z** [comment]
> @CrazyBoy49z что тут поправить нужно?)

Сейчас отправлю PR нужно будет только протестировать. С телефона неудобно было редактировать

**Comment by Ibochkarev** [comment]
Fixed #590
