### ISSUE TITLE
Расширить чанки письма и GetOrder

### ISSUE THREAD

**Issue by biz87** [modx-pro/miniShop2#582]
### Резюме / Summary

Информация о заказе, будь это чанк письма или чанк сниппета  GetOrder не содержат всю информацию, которую пользователь указал в заказе, хотя видеть ее довольно логично. 
Например нет указанного при заказе адреса.
Необходимо расширить выводимую информацию, чтобы у клиента и тем более администратора был доступ к введенной в заказе информации.

**Comment by alroniks** [comment]
Поддерживаю. Недавно столкнулся и пришлось дополнять вручную, хотя информация в самом деле необходимая.

**Comment by Ruslan-Aleev** [comment]
Связано с https://github.com/Ibochkarev/miniShop2/issues/378

**Comment by biz87** [comment]
{$order | print} - Таблица заказа
{$address | print} - Таблица адреса
{$delivery | print} - Таблица Доставки
{$payment | print} - Таблица оплаты
{$products | print} - Таблица товароы
