### ISSUE TITLE
Добавить return для всех сниппетов

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modx-pro/miniShop2#595]
### Резюме / Summary
Было бы удобно иметь возможность задавать, например, `'return' => 'json'` и для `msProducts`, `msGallery` и других сниппетов.

### Зачем это нужно / Why is it needed?
Для единообразия в работе сниппетов. Сейчас, например, для msGallery приходится создавать чанк.

**Comment by webinmd** [comment]
gallery return data #754
Добавлена поддержка параметра return в msProducts #553
Added return property to msProductOptions snippet #484
