### ISSUE TITLE
Загрузка нескольких файлов в галерею

### ISSUE THREAD

**Issue by jenusia1** [modx-pro/miniShop2#604]
При загрузке нескольких изображений (абсолютно разных с разными именами) выскакивает ошибка: "Такое изображение уже есть в галерее товара.". Адрес топика с вопросом https://modx.pro/help/12445.

**Comment by Ibochkarev** [comment]
https://github.com/vgrish/miniShop2/blob/master/core/components/minishop2/processors/mgr/gallery/upload.class.php#L204

**Comment by CrazyBoy49z** [comment]
> https://github.com/vgrish/miniShop2/blob/master/core/components/minishop2/processors/mgr/gallery/upload.class.php#L204

Судя по ошибке проблема здесь в создании объекта или в генерации хеша https://github.com/vgrish/miniShop2/blob/master/core/components/minishop2/processors/mgr/gallery/upload.class.php#L200

@jenusia1 более детально можете описать проблему?

**Comment by jenusia1** [comment]
Иногда, когда изображения хорошего качества и отличаются не значительно, то hash совпадает. В результате нет возможности загрузить изображение, поскольку ругается на ошибку. К сожалению, похожие изображения мне уже не найти.

**Comment by jenusia1** [comment]
Нашел 2 файла при которых возникает ошибка. https://yadi.sk/d/9IT8zZL5ShhDbw
