### ISSUE TITLE
Передача своих параметров в tpl

### ISSUE THREAD

**Issue by jenusia1** [modx-pro/miniShop2#609]
## Запрос функции / Feature request
Было бы здорово, поскольку сниппет msProducts наследуется от pdoResource, чтобы передача своих параметров в tpl так же поддерживалась. Очень часто бывают такие ситуации, когда это крайне необходимо.

### Зачем это нужно / Why is it needed?
Можно конечно использовать pdoResource с параметром element: msProducts, но это часто бывает неудобно.

**Comment by biz87** [comment]
Реализовано в 3.0.7
