### ISSUE TITLE
Создание вендора при создании товара

### ISSUE THREAD

**Issue by webinmd** [modx-pro/miniShop2#614]
### Резюме / Summary

При создании товара сделать возможность создавать и производителя

### Зачем это нужно / Why is it needed?

Сейчас чтобы привязать вендора к товару, его необходимо создать отдельно, в настройках, что не всегда удобно

Как это сделать не знаю, по логике необходимо привязать id производителя к товару, но у нас нет этого id, проблема получается примерно как с галереей. Хотя если в первую очередь создать производителя, получить сразу же его id и потом уже создавать товар, то возможно получится, Поправьте если не правильно понимаю логику

**Comment by biz87** [comment]
Тогда нужно менять тип поля с Autocomplete который обеспечивает только действие getList на что-то другое.

**Comment by biz87** [comment]
Здесь еще встает вопрос человеческого фактора.  Вдруг человек ошибся при вводе и некорректно написал имя вендора.

**Comment by Electrica** [comment]
Считаю такую возможность лишней, которая может запутать. Обычно, сначала создается производитель а потом под ним товары, а не наоборот

**Comment by alroniks** [comment]
> Считаю такую возможность лишней, которая может запутать. Обычно, сначала создается производитель а потом под ним товары, а не наоборот

Идеальный мир программиста. На деле никто так не делает. Потому что обычному менеджеру дают список товаров в виде таблицы и он ими наполняет сайт. Следовательно, у него нет мысли, что нужно наверное выделить сначала всех производителей, создать их, а потом выбирать в товарах. Только если не обучить этому предварительно. Поэтому с точки зрения удобства задача актуальна.

**Comment by Electrica** [comment]
> > Считаю такую возможность лишней, которая может запутать. Обычно, сначала создается производитель а потом под ним товары, а не наоборот
> 
> Идеальный мир программиста. На деле никто так не делает. Потому что обычному менеджеру дают список товаров в виде таблицы и он ими наполняет сайт. Следовательно, у него нет мысли, что нужно наверное выделить сначала всех производителей, создать их, а потом выбирать в товарах. Только если не обучить этому предварительно. Поэтому с точки зрения удобства задача актуальна.

А как это должно выглядеть? Создаю товар, просто вписываю производителя, и если его нет он его создает при сохранении?

**Comment by webinmd** [comment]
> > > Считаю такую возможность лишней, которая может запутать. Обычно, сначала создается производитель а потом под ним товары, а не наоборот
> > 
> > 
> > Идеальный мир программиста. На деле никто так не делает. Потому что обычному менеджеру дают список товаров в виде таблицы и он ими наполняет сайт. Следовательно, у него нет мысли, что нужно наверное выделить сначала всех производителей, создать их, а потом выбирать в товарах. Только если не обучить этому предварительно. Поэтому с точки зрения удобства задача актуальна.
> 
> А как это должно выглядеть? Создаю товар, просто вписываю производителя, и если его нет он его создает при сохранении?

Ну в идеале так и должно быть

**Comment by EMDM45** [comment]
Может просто рядом с полем выбора производителя как-то разместить кнопку?
При нажатии на эту кнопку возможны 2 вариант:
- открывать страницу с добавлением производителя в новой вкладке (т.е. кнопка - это просто ссылка).
или
- открывать модальное окно с формой создания нового производителя.

**Comment by biz87** [comment]
> Может просто рядом с полем выбора производителя как-то разместить кнопку? При нажатии на эту кнопку возможны 2 вариант:
> 
> * открывать страницу с добавлением производителя в новой вкладке (т.е. кнопка - это просто ссылка).
>   или
> * открывать модальное окно с формой создания нового производителя.

Да это пока пожалуй тот вариант - который может устроить всех. 
Если вообще заниматься этим запросом

**Comment by webinmd** [comment]
> > Может просто рядом с полем выбора производителя как-то разместить кнопку? При нажатии на эту кнопку возможны 2 вариант:
> > 
> > * открывать страницу с добавлением производителя в новой вкладке (т.е. кнопка - это просто ссылка).
> >   или
> > * открывать модальное окно с формой создания нового производителя.
> 
> Да это пока пожалуй тот вариант - который может устроить всех. Если вообще заниматься этим запросом

чем этот вариант проще, чем заменить поле и при сохранении товара создавать производителя?

**Comment by EMDM45** [comment]
> чем этот вариант проще, чем заменить поле и при сохранении товара создавать производителя?

"заменить поле" и "при сохранении создавать" может добавить новых ошибок, которые могут повлиять на работу системы (например, товар не будет сохраняться).
А если "добавить кнопку", как мне кажется, ничего не должно поломаться. Даже если кнопка не будет работать, максимум что произойдет - это человек не сможет создать нужного производителя. Но он сможет это сделать через раздел "производители" как сейчас.
Плюс будет использоваться уже готовый функционал по созданию: добавление фото, названия и других данных.

**Comment by webinmd** [comment]
> "заменить поле" и "при сохранении создавать" может добавить новых ошибок, которые могут повлиять на работу системы (например, товар не будет сохраняться).

ну так в том и смысл ,сделать удобно и без ошибок, если будут ошибки - PR не пройдет проверку и его не вольют. 
Я за удобные решения, а не за те что проще реализовать и быстрее влить.

**Comment by EMDM45** [comment]
> ну так в том и смысл ,сделать удобно и без ошибок, если будут ошибки - PR не пройдет проверку и его не вольют.

Ну, во-первых, сколько нужно будет времени, чтобы все это сделать, отработать, чтоб ошибок не было? Кстати, ошибки как-то автоматически проверяются? (новичок в этих всех технология github)
А, во-вторых, разве не могут быть баги уже после?

> Я за удобные решения

Понятие "удобства" у всех разное видимо. Для меня удобно вполне тот вариант, который предложил.

> а не за те что проще реализовать и быстрее влить

На мой субъективный взгляд, для начала можно сделать хотяб то что "проще реализовать и быстрее влить". И это уже будет облегчать людям жить.
Сейчас как раз пытаюсь в этом направлении поработать. Может что-то выйдет.

**Comment by biz87** [comment]
> Ну, во-первых, сколько нужно будет времени, чтобы все это сделать, отработать, чтоб ошибок не было? Кстати, ошибки как-то автоматически проверяются? (новичок в этих всех технология github)

Код автоматически тестируется на валидность и соответствие стандарту PSR-12.  Такой автоматический тест к слову можно включить в phpStorm.
Далее чистоту, качество и архитектуру кода проверяю в основном я.  Иногда еще несколько человек.  
Ну и на третьем этапе еще каждый PR устанавливаем на чистый сайт и пытаемся проверить внедряемый код уже в работе.
