### ISSUE TITLE
Проблема с динамическим обновлением суммы скидки в корзине

### ISSUE THREAD

**Issue by suvoroff** [modx-pro/miniShop2#616]
`<div class="ms2_total_discount">{$total.discount}</div>`

Вывод суммы скидки корректен только при обновлении страницы. При динамическом изменении кол-ва товаров в корзине  - вместо обновления суммы скидки отдаётся 0.

**Comment by biz87** [comment]
Проверил.  Все прекрасно работает, проблемы не наблюдаю.

**Comment by suvoroff** [comment]
Да, прошу прощения. Тоже проверил, если в поле old_price внесено значение напрямую, то все считается и обновляется корректно. Данная проблема имеет место быть в комплексе с работой компонентов для скидок, в частности msDiscount, когда поле old_price по факту остается пустым. В этом случае {$total.discount} считается только при обновлении страницы
