### ISSUE TITLE
В связях нужно указать какой товар будет главным

### ISSUE THREAD

**Issue by Electrica** [modx-pro/miniShop2#643]
## Запрос функции / Feature request

Когда создаем связь, не понятно, какой товар будет главным.

![image](https://user-images.githubusercontent.com/3878386/140919908-7090c469-e71f-4170-9033-0419e40170cc.png)

### Зачем это нужно / Why is it needed?
Если в скообочках указаать, на пример Один ко многим(Созданный товар будет главным), Многие к одному(созданный товар будет подчиненным)

**Comment by biz87** [comment]
А разве один товар обязательно должен быть главным?
Например, в связи один к одному - оба товара могут быть равноправными

**Comment by alroniks** [comment]
Так и нужно пояснить детальнее. Я сам часто путаюсь, приходится код смотреть или эксперименты делать

**Comment by Electrica** [comment]
> А разве один товар обязательно должен быть главным? Например, в связи один к одному - оба товара могут быть равноправными

вот на пример, я хочу сделать, что бы создаваемый товар был главным. Какой из пунктов "Один ко многим" или "Многие к одному" подходят?

**Comment by Electrica** [comment]
![image](https://user-images.githubusercontent.com/3878386/142442038-9027102e-9f56-4aa9-bfb7-0afa7ef40263.png)
Вроде в последней версии, скаченной с гита есть подсказка. Поэтому, считаю ишью закрытой
