### ISSUE TITLE
При обновлении цены через Enter, в списке товаров (админка), происходит переход в начало списка

### ISSUE THREAD

**Issue by kos0760** [modx-pro/miniShop2#646]
### Резюме / Summary

В админке, в списке товаров есть возможность быстрого редактирования цен двойным кликом. Но когда обновляешь цену и жмешь Enter, перебрасывает в начало списка товаров. Если прописать новую цену, отвести курсор и нажать мышкой в любом месте, тогда цена сохраняется и в начало списка не перебрасывает. 

https://user-images.githubusercontent.com/25278076/141303066-1542abd5-d15b-4463-9436-823a9bd657b8.mp4

### Зачем это нужно / Why is it needed?

Через Enter менеджерам удобно быстро и последовательно обновлять цены в товарах. Т.е. пишем в поле новую цену, жмем Enter и курсор сразу переходит в поле цены следующего товара, где сразу тоже можно обновлять цену и т.д.

**Comment by biz87** [comment]
Как по мне по нажатию Enter должно происходить сохранение и на этом все. 
Никаких перебросов на другие строчки, быть не должно.

**Comment by Electrica** [comment]
Ага, и потом будет, после нажатия нужно будет тыкнуть еще куда то, что бы цену следующего товара не затереть

**Comment by kos0760** [comment]
Ну я как бы не настаиваю. Просто если взять версию минишопа 2.4.18, с которой я обновился до 2.9.3, то там было очень удобно обновлять цены через Enter. Особенно если нужно в админке быстро поменять цены у товаров, отличающиеся, например, только цветом. И они в списке товаров идут один за одним.

https://user-images.githubusercontent.com/25278076/141453390-209347a7-2f6c-4dfc-b61d-ed74c31fd616.mp4

Теперь мне звонят менеджеры и просят вернуть как было до последнего обновления минишопа. Только на старую версию опять особо не хочется переходить.

**Comment by Ruslan-Aleev** [comment]
Ну в целом, это актуально для сетки товаров, удобно. Но я не знал, что такое было когда-то =)
p.s. Такое поведение в офисных приложениях есть, аля Excel, поэтому не удивительно, что менеджеры привыкли к этому.

**Comment by Ruslan-Aleev** [comment]
Можно настройку, наверное добавить, вот это отвечает за редактирование строк:

https://github.com/Ibochkarev/miniShop2/commit/cb35e3f3dfca4883b692b1d0ffcbdd4f5f7523ed#diff-a0526dcf15576e25cdd9064cff5d1de0885d70fd81579596bf5105765df61d83R172

**Comment by Ruslan-Aleev** [comment]
Можно настройку, наверное, создать. Вот этот код за это отвечает: https://github.com/Ibochkarev/miniShop2/commit/cb35e3f3dfca4883b692b1d0ffcbdd4f5f7523ed#diff-a0526dcf15576e25cdd9064cff5d1de0885d70fd81579596bf5105765df61d83R172

Было убрано в https://github.com/Ibochkarev/miniShop2/pull/337
