### ISSUE TITLE
miniShop2 роняет админку с 500 на php 5.6

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modx-pro/miniShop2#647]
### Резюме / Summary
На старых версиях php miniShop2 уронит админку с 500 ошибкой.
Т.к. MODX 2 и другие компоненты MODX работают на php 5.6, то требования miniShop2 к минимальной php 7 - как-то странновато.
Мало того, в доках стоит PHP не ниже 5.3.

### Ожидаемое поведение / Expected behavior
При установки/обновлении нужно добавить проверку требований, иначе можно уронить админку.
Или вернуть поддержку старых версий, а php 7 уже оставить для MODX 3.

Требования к php изменились после https://github.com/Ibochkarev/miniShop2/pull/620

### Environment
miniShop2 2.9.3
php 5.6

**Comment by alroniks** [comment]
Возвращать поддержку старых версий нельзя. Ответ простой - есть end of life продукта или версии, в случае PHP - все, что старше php 7.2 включительно, больше не поддерживается вообще никак. Даже нет обновлений безопасности. Исправить документацию нужно, не спорю. Сделать проверку версии - тоже. Но никак не занижая версию в угоду ленивым сисадминам. MODX тоже давно пора было обновить до более свежих версий, но тоже были подобные рассуждения и сошлись, что это будет уже в 3 версии. И на том спасибо.

**Comment by Ruslan-Aleev** [comment]
> Но никак не занижая версию в угоду ленивым сисадминам.

Тут версия php изменилась в 2.9.3, на фоне, в 2.9.2 все норм. Я понимаю, если это мажорная версия, или какие-то глобальные правки кода, но тут версию повысили, чтоб было.
По такому же принципу, можно в других пакетах добавлять немотивированное использование функций из php 7, только чтоб ленивые админы обновляли версию php.

Я за обновление, но чтоб оно было привязано к мажорной версии, или оправдано кодом.

**Comment by Ruslan-Aleev** [comment]
Нужна проверка требований при установке/обновлении, просто закрыть issue - не особо продуктивно =)

**Comment by biz87** [comment]
> Нужна проверка требований при установке/обновлении, просто закрыть issue - не особо продуктивно =)

Сделаю
