### ISSUE TITLE
msOnGetProductPrice не работает так как надо?

### ISSUE THREAD

**Issue by EMDM45** [modx-pro/miniShop2#649]
### Резюме / Summary

Пытался решить такую задачу.
Дано: 
1) Товар, у которого цена 10 000.
2) Два одинаковых плагина на событие msOnGetProductPrice.

Нужно сделать, чтобы каждый плагин добавлял +1 000 к стоимости товара.
В итоге стоимость должна быть 12 000.

П.С. понятно, что пример утрирован, мне важно было понять как работает это событие.

### Шаг для воспроизведения / Step to play

У плагина такой код:
```
if(isset($modx->event->returnedValues['price'])){
        
    $price = $modx->event->returnedValues['price'];
    
}
    
$newprice = $price + 1000;

$modx->event->returnedValues['price'] = $newprice;

$modx->log(1, 'price: '.$price);
$modx->log(1, 'new: '.$newprice);
```

### Наблюдаемое поведение / Observed behavior

Возможно я что-то делаю не так или так и задумано, но у меня всегда получается стоимость 11 000.

### Ожидаемое поведение / Expected behavior

В моем понимании должно быть 12 000.

### Environment

Версия miniShop2 - 2.9.3-pl,
версия MODX - 2.8.3

**Comment by pashajanx** [comment]
Привет, поставь разные приоритеты у плагинов на событие msOnGetProductPrice

**Comment by EMDM45** [comment]
> 

Поставил одному 1, второму 2.
Результат прежний.

```php
$p = $modx->getObject('msProduct', 9);

echo $p->getPrice(); //11 000
```
В логах:
```
price: 10 000
new: 11 000
price: 10 000
new: 11 000
```

**Comment by EMDM45** [comment]
Допускаю, что это на уровне MODX такое происходит.

**Comment by EMDM45** [comment]
Как я понимаю этот баг так и не исправили))
https://github.com/modxcms/revolution/issues/15056

**Comment by EMDM45** [comment]
I have a problem with it too
