### ISSUE TITLE
Объеденить  сниппеты корзины и оформления заказа в один

### ISSUE THREAD

**Issue by webinmd** [modx-pro/miniShop2#657]
### Резюме / Summary

Объединить 3 сниппета в один со всем набором переменных.
Вместо msCart/msOrder/msGetOrder - сделать оджин общий. Оставить возможность вызывать его сколько угодно раз на странице

### Зачем это нужно / Why is it needed?

На мой взгляд было бы удобнее прикрутить любой дизайн и обновлять любые поля.

### Предлагаемое решение(я) / Proposed solution (s)

На первое время сделать отдельный общий сниппет, а потом как-то в мажорной версии убрать. Потеряется возможность обновления возможно.

**Comment by Electrica** [comment]
только я бы оставил msGetOrder отдельно. Частенько он нужен для оформления где нибудь в другом месте. Хотя хз

**Comment by Semdevmaster** [comment]
Не вижу смысла в объединении этих сниппетов, так как текущая реализация с 3 отдельными сниппетами дает больше гибкости. Есть магазины, у которых корзина и оформление заказа это принципиально разные этапы бизнес процесса, они на отдельных страницах, по каждому идет своя статистика, своя логика, свои требования.

**Comment by EMDM45** [comment]
Не совсем понял "зачем это нужно" ? А сейчас разве нельзя любой дизайн прикрутить? В таком случае хочется какие-то более конкретные примеры услышать.

Вообще лично я воспринимаю сниппеты как функции. Т.е. 1 функция = 1 сниппет.
И поддерживать проще разные сниппеты, чем одну портянку на миллион строк))

**Comment by webinmd** [comment]
> Не совсем понял "зачем это нужно" ? А сейчас разве нельзя любой дизайн прикрутить? В таком случае хочется какие-то более конкретные примеры услышать.
> 
> Вообще лично я воспринимаю сниппеты как функции. Т.е. 1 функция = 1 сниппет. И поддерживать проще разные сниппеты, чем одну портянку на миллион строк))

2 года назад я был молод и глуп

**Comment by biz87** [comment]
ООП требует не писать один и тот же код, а выносить его в отдельный метод и переиспользовать. 
Сниппеты имеют много общего кода выборки и инициализации. 
Кроме того они очень большие, что по парадигме программирования неверно. 
Нужно переносить эту архитектуру в класс, бить на методы, использовать общие методы.  
А в сниппете вызывать метод, давая возможность пользователю дополнить итоговые данные где нужно
