### ISSUE TITLE
Нулевая стоимость заказа и онлайн оплата

### ISSUE THREAD

**Issue by webinmd** [modx-pro/miniShop2#658]
### Резюме / Summary

При нулевой стоимости заказа все равно происходит редирект на страницу онлайн оплаты.
Например, если использовать промокоды и получить стоимость заказа = 0, то при редиректе на оплату мы получим ошибку (нельзя оплатить 0 рублей). Как бы логично, но получаем ошибку уже на стороне платежки, а не самого минишопа

### Шаг для воспроизведения / Step to play

Использовать компонент промокода или попытаться оплатить товар с нулевой ценой

### Наблюдаемое поведение / Observed behavior

Редирект на страницу оплаты с ошибкой со стороны сервиса оплаты

### Ожидаемое поведение / Expected behavior

Не редиректить в платежку. Можно было бы добавить в системные настройки в какой статус переводить такие заказы

### Environment

Версия miniShop2 2.8.3

**Comment by Electrica** [comment]
А есть ли это баг как таковой?

**Comment by webinmd** [comment]
> А есть ли это баг как таковой?

а вот не понятно, какое поведение было бы верным?

**Comment by Electrica** [comment]
> > А есть ли это баг как таковой?
> 
> а вот не понятно, какое поведение было бы верным?

по мне это не проблема или баг системы. Заказ с нулевой суммой вполне может быть и часто встречается. А то что платежки его не принимают, вот тут наверное вопрос к платежке

**Comment by webinmd** [comment]
> вот тут наверное вопрос к платежке

тестировал на двух разных платежках.

**Comment by Electrica** [comment]
> > вот тут наверное вопрос к платежке
> 
> тестировал на двух разных платежках.

ну тут два варианта. Оставить все как есть и дать возможность разработчику расширить класс заказа и там уже рулить редиректом, либо добавить настройку, которая не даст редирект при нулевой стоиомсти.....но что дальше?
