### ISSUE TITLE
В шаблонах писем массив {$products} не содержит TV

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modx-pro/miniShop2#667]
### Резюме / Summary
Для msGetOrder в доках https://docs.modx.pro/komponentyi/minishop2/snippetyi/msgetorder сказано, что можно через `includeTVs` добавить TV, то в массиве `products` (массив заказанных товаров со всеми их свойствами) так же будет доступны TV, все норм, все работает.

Можно проверить, вызвав `<pre>[[!msGetOrder?tpl=``]]</pre>` (TV будут в массиве).

НО, в чанках писем массив `products` передается уже без TV, хотя в доках указано иначе:

"Все переменные сниппета msGetOrder: order, **products**, user, address, delivery, payment и total также доступны для использования в письмах почтовых уведомлений."

Что путает.

### Ожидаемое поведение / Expected behavior
Стоит передавать и TV в массив `products` для писем (или поправить доку :))

### Environment
miniShop2 2.9.3-pl, MODX 2.8.3

**Comment by Electrica** [comment]
Видение решения такое:

Так как в письме вызов сниппета msGetOrder без параметра includeTVs

1. Можно создать настройку в общих настройках для записи списка вывода ТВ в письме, и создать настройку в каждом статусе, для указания возможно разных ТВ, приоритет именно у статуса
2.  Выбирать ВСЕ привязанные ТВ к каждому товару и передававать полный список ТВ в вызов сниппета в письме

**Comment by Ruslan-Aleev** [comment]
После обсуждения, мне кажется, что 1. вариант в настройках статусов более логичный.
Тем более, как указал Миша, TV не часто нужны в письмах, т.е. доп. нагрузки не появится, если что. Хотя именно мне требовались TV в письме.

**Comment by Ruslan-Aleev** [comment]
Реализовано в https://github.com/modx-pro/miniShop2/pull/832
