### ISSUE TITLE
В английском лексиконе присутствует слово "Стутус"

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modx-pro/miniShop2#669]
В английском лексиконе присутствует слово "Стутус" на кирилице, см. `ms2_statuses_intro` - https://github.com/modx-pro/miniShop2/blob/28df070265225193741f54d43b3adeb0774432a7/core/components/minishop2/lexicon/en/default.inc.php#L36

`... "cancelled". Стутус can be fixed ...`

**Comment by Ibochkarev** [comment]
Fixed #687
