### ISSUE TITLE
Интерфейс для импорта

### ISSUE THREAD

**Issue by webinmd** [modx-pro/miniShop2#676]
### Резюме / Summary

Написать минимальный интерфейс для использования встроенного импорта

### Зачем это нужно / Why is it needed?

Удобно

**Comment by Electrica** [comment]
Вот очень удобный трейт для импорта. Можно что то +- по дизайну и функционалу сделать
![image](https://user-images.githubusercontent.com/3878386/161528226-46a9e525-4e7f-48be-be95-3644b66ba3d6.png)

**Comment by webinmd** [comment]
> Вот очень удобный трейт для импорта. Можно что то +- по дизайну и функционалу сделать 

ну это уже тянет на отдельный компонент, я предлагаю сделать минимальный хотя бы, но интуитивно понятный

**Comment by Electrica** [comment]
> > Вот очень удобный трейт для импорта. Можно что то +- по дизайну и функционалу сделать
> 
> ну это уже тянет на отдельный компонент, я предлагаю сделать минимальный хотя бы, но интуитивно понятный

Ну справедливости ради у нас есть msImportExport
