### ISSUE TITLE
Некорректная работа после обновления с 3.0 на 3.03

### ISSUE THREAD

**Issue by kaiwas** [modx-pro/miniShop2#691]
Здравствуйте.

После обновления 3.0->3.03 превьюшка отображается только последняя из загруженных. Т.е. если их перетаскивать туда-сюда - обновление главной не происходит.
Так же дубль товара не переносится в соседнюю категорию. У меня проекты домов в исходном виде по адресу /projects/.... а зеркальные по адресу /projects-mirror/..... Создаю оригинал, дублирую и дубликат переношу в зеркальную категорию.

Так вот сами ссылки принимают правильный вид, но витрина считает что зеркальный вариант остаётся потомком изначального родителя.
проверял вывод в msProducts , mFilter2, pdoResources - везде итог одинаковый.

Пока откатился на 3.0

### Шаг для воспроизведения / Step to play

У меня это просто обновление с 3.0 на 3.03 и добавление нового товара. Затем его дублирование с небольшими изменениями текста и перенос дубликата в другую категорию.

### Наблюдаемое поведение / Observed behavior

Не правильный вывод товара на витрину. Какие-либо изменения не помогают.

Версия miniShop2- 3.03
версия MODX - 2.8.4, 
Nginx - 1.14.1
версия mysql - 5.7.38
браузер - firefox, chrome

**Comment by spokik** [comment]
Я вообще далек от всего этого, я вообще не могу на modx 3 поставить miniShop2

**Comment by webinmd** [comment]
> Я вообще далек от всего этого, я вообще не могу на modx 3 поставить miniShop2

потому что miniShop пока что не поддерживает модх3

**Comment by spokik** [comment]
> 

А, понял, речь про версию расширения. окей. Пойду ставить по инструкции
