### ISSUE TITLE
Ошибка в minishop2.mysql.schema.xml

### ISSUE THREAD

**Issue by topor-topor** [modx-pro/miniShop2#693]
## Сообщение об ошибке / Error message
при установке:
```
Error adding field msOrderStatus->: Array ( [0] => 42000 [1] => 1166 [2] => Incorrect column name '' )
Added field "" of the table "msOrderStatus"
```
в журнале ошибок:
```
[2022-06-09 16:43:55] (ERROR @ {...}/core/xpdo/om/xpdoobject.class.php : 240) Error 42S22 executing statement: 
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'msOrderStatus.' in 'field list'
)
```

### Резюме / Summary

В файле схемы ошибка в описании поля rank класса msOrderStatus, поэтому оно нормально не создается/не обновляется.
В файле msorderstatus.map.inc.php ошибка с пустым ключом поля.

### Наблюдаемое поведение / Observed behavior

не работают статусы заказа полностью, ни в админке, ни при создании заказа

### Environment

Версия miniShop2 3.0.4-pl
версия MODX 2.8.4-pl

**Comment by perfkirill** [comment]
Точно такая же ошибка, нет возможности оформить заказ, в логах такая же ошибка.

Версия miniShop2 3.0.4-pl
версия MODX 2.8.4-pl
хостинг timeweb

**Comment by webinmd** [comment]
подтверждаю, после обновления до версии 3.0.4 ~~очистилась таблица со статусами~~ - не подгружаются статусы

**Comment by webinmd** [comment]
Временное решение:
1) создать поле rank в таблице ms2_order_statuses
2) в файле core/components/minishop2/model/minishop2/mysql/msorderstatus.map.inc.php исправить для поля rank ключ (там пустой ключ)
3) в схеме регистр сменить на нижний для таблицы ms2_order_statuses у поля Key="rank"
