### ISSUE TITLE
Не показываются данные о заказе в CRM minishop2

### ISSUE THREAD

**Issue by perfkirill** [modx-pro/miniShop2#695]
При создании заказа  имя, телефон, email записываются в БД, но в админке в CRM не показываются.

в логе ошибка 
core/xpdo/om/xpdoquery.class.php | 770
Encountered empty IN condition with key id

php 7.1
minishop 3.0.4-pl2

Также такое наблюдается на версии 3.0.0-pl, дополнительные ошибки возникают, когда включаешь, отключаешь какие-либо сторонние плагины

12.06.2022 | 10:08:29 | ERROR | /public_html/core/xpdo/xpdo.class.php | 644

Could not load class: pdofetch from pdotools.pdofetch.

ERROR |/public_html/core/xpdo/xpdo.class.php | 1248

Problem getting service pdoFetch, instance of class pdotools.pdofetch, from path

ERROR | /core/components/minishop2/model/minishop2/minishop2.class.php | 640
pdoTools not installed, metadata for miniShop2 objects not loaded

**Comment by biz87** [comment]
Подобное поведение не подтверждается.  На третьей версии работают десятки сайтов уже.  Возможно сторонние плагины у вас и шалят.

**Comment by perfkirill** [comment]
Хорошо, вполне возможно, что проблема с каким- то модулем. Я снес все, установил все модули на чистое ядро (сбоку, кому как угоднее), ошибки повторяются. (однако я не смог установить последнюю версию и взял версию 2.9.3-pl с работающего проекта)


Теперь сношу еще раз и вообще не могу установить minishop2, точно также как было в тот раз. у меня постоянное зависание https://disk.yandex.ru/i/WkVnDttbC2JMSw


А кстати прикол. У меня вообще- то все работало, но были ошибки
```
12.06.2022 | 10:08:29 | ERROR | /public_html/core/xpdo/xpdo.class.php | 644
Could not load class: pdofetch from pdotools.pdofetch.
ERROR |/public_html/core/xpdo/xpdo.class.php | 1248
Problem getting service pdoFetch, instance of class pdotools.pdofetch, from path
ERROR | /core/components/minishop2/model/minishop2/minishop2.class.php | 640
pdoTools not installed, metadata for miniShop2 objects not loaded
```

Я подумал, что обновив до последней версии все будет ок, обновил (почему-то в этот раз вышло скачать с репозитория) и.... У меня снова не записываются данные в CRM

**Comment by perfkirill** [comment]
Нет, проблема у вас, поставил я все таки ,minishop последний модулей там нет, повторяются ошибки 
вот список модулей https://disk.yandex.ru/i/kAf2oONtTwhY-g

Вызвать ошибки можно просто деактивировав, а потом включить любой плагин
https://disk.yandex.ru/i/53p3I0CH_8CitQ

**Comment by biz87** [comment]
Обновите до версии  3.0.5

**Comment by perfkirill** [comment]
Обновил до версии 3.0.5 все равно при отключении плагина и включении ошибка, пока что оно все работает, но почему такая ошибка возникает и как ее убрать? Потестируйте на хостинге timeweb



21.06.2022 | 07:35:55 | ERROR | public_html/core/xpdo/xpdo.class.php | 644
-- | -- | -- | -- | --
Could not load class: pdofetch from pdotools.pdofetch.
  | 21.06.2022 | 07:35:55 | ERROR | public_html/core/xpdo/xpdo.class.php | 1248
Problem getting service pdoFetch, instance of class pdotools.pdofetch, from path
  | 21.06.2022 | 07:35:55 | ERROR | public_html/core/components/minishop2/model/minishop2/minishop2.class.php | 642
pdoTools not installed, metadata for miniShop2 objects not loaded



> Обновите до версии 3.0.5
