### ISSUE TITLE
Не отправляются письма менеджеру

### ISSUE THREAD

**Issue by webinmd** [modx-pro/miniShop2#706]
### Резюме / Summary

Не отправляются письма менеджеру. Покупателю все письма приходят исправно

### Шаг для воспроизведения / Step to play

Оформить заказ и ожидать письмо что "У вас новый заказ"

### Наблюдаемое поведение / Observed behavior

Письмо покупателю приходит, менеджеру (менеджерам) - нет.

 

### Environment

Версия miniShop2 3.0.0, 
версия MODX 2.8.4, 
PHPMailer 6.5.1, 
mysql  5.7.38-0ubuntu0.18.04.1

**Возникновение проблемы и Решение:** 

если создать пользователя с email-ом, совпадающим с каким-либо email-ом менеджера, все — отправка почты всем менеджерам отваливается.

После переписывания всех email менеджеров и удаления пользователей, проблема больше не наблюдается.
[Источник решения](https://modx.pro/help/13664)

**Comment by Ruslan-Aleev** [comment]
Подтверждаю, думал, что где-то в настройках это указано, но нет. Само не отправляет =)

**Comment by biz87** [comment]
Это условности хостинга скорее всего.  Технически в minishop с подобными вещами проблем нет.

**Comment by Ruslan-Aleev** [comment]
@biz87 Это точно из-за хостинга? Лучше перепроверить.

**Comment by biz87** [comment]
@Ruslan-Aleev в минишопе нет никакой привязки отправки писем к юзерам.  Туда тупо перечень email через запятую загоняется и все. Отправляет письма встроенный механизм MODX - там тоже нет никаких привязок к юзерам.  Только emailsender и получатели.   Кроме того не везде эта проблема наблюдается. За все годы всего несколько человек отписались.  
Я бы сказал так - нет ничего такого что мы могли бы сделать в рамках компонента.
