### ISSUE TITLE
miniShop2-4.0.0-beta При создании заказа из админки в консоли ошибка записи в таблицу modx_ms2_order_addresses

### ISSUE THREAD

**Issue by Semdevmaster** [modx-pro/miniShop2#731]
## Сообщение об ошибке / Error message
```
Error HY000 executing statement:
INSERT INTO `modx_ms2_order_addresses` (`user_id`, `createdon`) VALUES (1, '2022-09-19 16:28:16')
Array
(
    [0] => HY000
    [1] => 1364
    [2] => Field 'order_id' doesn't have a default value
)
```
### Наблюдаемое поведение
При создании заказа из админки в консоли ошибка записи в таблицу modx_ms2_order_addresses

### Environment
miniShop2-4.0.0-beta
MODX 2.8.4
PHP 7.4
MySQL 5.7

**Comment by biz87** [comment]
Уже пофиксино и влито в мастер ветку. 
А вот релиз обновить наверное забыли.

**Comment by biz87** [comment]
Еще раз перепроверил.  С последними доработками все работает как надо, без ошибок
