### ISSUE TITLE
Проблема с установкой на версию modx 3.0.2-pl

### ISSUE THREAD

**Issue by DylVadim** [modx-pro/miniShop2#746]
После обновления до свежей версии modx 3.0.2-pl невозможно установить т.к. пишет что требуется версия < 3.0.0

Версия miniShop2 - 3.0.7-pl, версия MODX - 3.0.2-pl

![image](https://user-images.githubusercontent.com/54818214/203994852-9da789a9-fca5-4d8d-902f-5f59d59903a4.png)

**Comment by biz87** [comment]
Все верно.  miniShop2 работает только на второй версии MODX.

**Comment by DylVadim** [comment]
А нет каких либо обходных путей? 😊

**Comment by biz87** [comment]
> А нет каких либо обходных путей? 😊

Нет.  MODX3 - это другой программный продукт, со своей отличающийся логикой и принципами работы.
