### ISSUE TITLE
Перепроверить процессоры галереи

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modx-pro/miniShop2#758]
### Резюме / Summary

Перепроверить процессоры удаления фоток в галереи: `gallery/removeall,  gallery/multiple -> remove`, возможно и другие.
Насколько помню они не срабатывали, но тут не уверен.

**Comment by Electrica** [comment]
Работаю, проверил удаление по одному а так же все или несколько. Все отрабатывает корректно

**Comment by Ruslan-Aleev** [comment]
@Electrica Понял, хорошо, спасибо.
Тогда закрываю, как проверенное в https://github.com/modx-pro/miniShop2/pull/811
