### ISSUE TITLE
Интегрировать лексиконы с сервисами перевода

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modx-pro/miniShop2#765]
### Резюме / Summary
Интегрировать лексиконы miniShop с сервисами перевода, например, crowdin.
Выбрать главным языком русский (как самый наполненный), и на основе создавать/обновлять переводы.
А то куча строк в некоторых языках вообще без перевода.

### Зачем это нужно / Why is it needed?
Будет удобнее управлять лексиконами, как сейчас работает в MODX.
Поправили главный язык, crowdin сообщил участникам, что нужно добавить переводы.

**Comment by Ibochkarev** [comment]
Это уже есть, и проект есть. Нужно только сделать только саму интеграцию

**Comment by Ruslan-Aleev** [comment]
Так, вот подробный видос по интеграции - https://www.youtube.com/watch?v=8baL6VWnnZg
У кого доступа есть, можно заняться, я бегло посмотрел - визуально понятно и недолго, вроде.

**Comment by Ruslan-Aleev** [comment]
Еще нужно проверить дубли ключей, удалить комменты, удалить папку `gr` (сейчас в MODX ключ `el` для греческого), отсортировать строки по алфавиту ключей и добавить ссылку в readme на crowdin.
Заметил, что есть повторяющиеся строки при интеграции.

**Comment by Ruslan-Aleev** [comment]
Сделано, см. https://crowdin.com/project/minishop2-ecommerce
