### ISSUE TITLE
Вынести регулярку валидации телефона в системные настройки

### ISSUE THREAD

**Issue by biz87** [modx-pro/miniShop2#770]
Регулярка в сис. настройках — идеально. Ею можно регулировать и длину, и запятые и добавочные номера через # и DTMF-коды и что хочешь под любой функционал.

Для мультиконтекстных сайтов её можно будет перезаписывать настройками контекстов, переопределять в плагинах и т.п.

**Comment by Electrica** [comment]
@biz87 закинул коммит, правда не в тот пул реквест но думаю пойдет
