### ISSUE TITLE
Не добавляется ms2_category_content_default при быстром создании категории

### ISSUE THREAD

**Issue by MazheM** [modx-pro/miniShop2#82]
При быстром создании категории не вставляется содержимое категории по умолчанию. Это баг или это просто нельзя сделать?

**Comment by bezumkin** [comment]
Пока это нельзя сделать, ибо быстрые окошки рисуются оригинальными скриптами MODX и там нет такого понятия, как "содержимое по умолчанию".

Может быть, доберусь и до них, когда-нибудь.
