### ISSUE TITLE
Ошибка в модели msOrderAddress

### ISSUE THREAD

**Issue by pashajanx** [modx-pro/miniShop2#826]
## Сообщение об ошибке / Error message
`INSERT INTO `xxxxx_ms2_order_addresses` (`user_id`, `createdon`) VALUES (1, '2023-03-28 18:49:30')
Array
(
    [0] => HY000
    [1] => 1364
    [2] => Field 'order_id' doesn't have a default value
)`

### Резюме / Summary
При попытки создать объект msOrderAddress выдает ошибку.
Такое поведение наблюдаю при использование MariaDB. 

### Шаг для воспроизведения / Step to play
При создание заказа через метод submit 
`$ms2 = $modx->getService('minishop2');`
`$ms2->initialize('web', array('json_response' => true, 'allow_unpublished' => 1));`
    `$ms2->cart->add($modx->resource->id, 4, []);`
    `$ms2->order->add('phone', '1234567890');`
    `$ms2->order->add('rules', true);`
    `$ms2->order->add('receiver', 'test');`
    `$ms2->order->add('delivery', 1);`
    `$ms2->order->add('payment', 1);`
    `$response = $ms2->order->submit();`

При создание объекта msOrderAddress
`$users = $modx->user->getOne('Profile');`
`$address = $modx->newObject('msOrderAddress', [
    'user_id' => $users->get('id'),
    'createdon' => time()
]);`
`$address->save();`

### Ожидаемое поведение / Expected behavior

Присваивание order_id 0 значение.

### Решение 
Добавить полю order_id по умолчанию 0 значение.

### Environment
Modx 2.8.5
miniShop2 4.1.3-pl, 
DB: 10.3.28-MariaDB-1:10.3.28+maria~focal

**Comment by Ibochkarev** [comment]
Fixed #827
