### ISSUE TITLE
msProducts не возвращает опции товара при return json

### ISSUE THREAD

**Issue by ldrshv** [modx-pro/miniShop2#842]
msProducts не возвращает опции товара при return json. Но если указать пустой tpl, то опции выводятся. Может пока какой-нибудь костыль посоветуете? А то приходится в каждой карточке товара вызывать сниппет для получения опций.

Версия 4.1.4

**Comment by webinmd** [comment]
Вскрылась еще одна проблема, при return json в сниппете пропускается большой кусок кода, в котором запускаются плагины  **msOnGetProductPrice msOnGetProductWeight msOnGetProductFields**, а также пропускается сниппет модификации цены. 
Как один из вариантов решения можно после получения 
`$rows = $pdoFetch->run(); `

делать json_decode
И затем, после полной обработки снова json_encode. 
Не уверен что это правильное решение, подождем, может кто подскажет получше
