### ISSUE TITLE
Проблема доп. стоимости доставки, если она указана в процентах

### ISSUE THREAD

**Issue by avdant** [modx-pro/miniShop2#845]
При указании доп. стоимости доставки в процентах, после оформления заказа стоимость доставки добавляется к общей стоимости корзины, а сама стоимость доставки становится 0. При указании стоимости доставки фиксированной суммой такой проблемы нет.
Проблема мне кажется вот в этом месте: components/minishop2/handlers/msdeliveryhandler.class.php
```
public function getCost(msOrderInterface $order, msDelivery $delivery, $cost = 0.0)
    {
        if (empty($this->ms2)) {
            $this->ms2 = $this->modx->getService('miniShop2');
        }
        if (empty($this->ms2->cart)) {
            $this->ms2->loadServices($this->ms2->config['ctx']);
        }
        $cart = $this->ms2->cart->status();
        $weight_price = $delivery->get('weight_price');

        $cart_weight = $cart['total_weight'];
        $cost += $weight_price * $cart_weight;

        $free_delivery_amount = $delivery->get('free_delivery_amount');
        if ($free_delivery_amount > 0 && $free_delivery_amount <= $cart['total_cost']) {
            $add_price = 0;
        } else {
            $add_price = $delivery->get('price');
            if (preg_match('/%$/', $add_price)) {
                $add_price = str_replace('%', '', $add_price);
                $add_price = $cost / 100 * $add_price;
            }
        }

        $cost += $add_price;

        return $cost;
    }
```

Вот здесь $cost (выделил жирным) будет равна 0, а если будет указана надбавка за вес, то сумме рассчитанной только за вес.
$add_price = $delivery->get('price');
            if (preg_match('/%$/', $add_price)) {
                $add_price = str_replace('%', '', $add_price);
                $add_price = **$cost** / 100 * $add_price;
            }
Поэтому когда доп. стоимость - фиксированная сумма, мы получаем корректную стоимость доставки из $delivery->get('price');
Но когда проценты, мы начинаем считать от $cost, а в ней нет стоимости корзины.
Я заменил $cost на $cart['total_cost'], мне подошло вроде, но может это не совсем верно.

**Comment by webinmd** [comment]
не смог воспроизвести на версии 4.1.3-pl

**Comment by avdant** [comment]
проблема обнаружилась на 4.1.0.
Проверил на голом modx + minishop 4.1.5 - проблема есть.
Может я не так объяснил. В момент оформления заказа все хорошо. Доставка обнуляется уже при сохранении заказа и в админке отображается уже 0, а стоимость покупок увеличивается на стоимость доставки. Это только при доп. стоимости в процентах.
На скринах заказ на 1000 рублей (доставка стоит 10%). После оформления доставка стала 0, стоимость покупок 1100
![image](https://user-images.githubusercontent.com/20616319/231042063-1164e126-30ce-402c-9c90-6c89de366085.png)
![image](https://user-images.githubusercontent.com/20616319/231042357-77a73ecc-aa24-4ace-97dd-984f2e73f2a5.png)
![image](https://user-images.githubusercontent.com/20616319/231042453-5f19d633-0685-474c-b621-f92f7227ab10.png)

**Comment by webinmd** [comment]
>  После оформления доставка стала 0, стоимость покупок 1100 !

Теперь понял, смотрел на стоимость до отправки заказа, на странице оформления.

Ошибку подтверждаю.

**Comment by webinmd** [comment]
Господа есть ньюанс по рассчету стоимости доставки, у нас ее цена может зависеть от нескольких пунктов
1) Доп стоимость (фиксированно или в процентах)
2) От веса
3) От расстояния

Есть ньюанс с процентами этими
Приведу на примере
Есть товар 
- Стоимость 100р
- Вес 100гр 

Условия: 
Доставка: 10%
Стоимость ед/вес: 1р (1 рубль за 1 грамм) 

ВАРИАНТ 1:
Получаем стоимость доставки 
10р + 100р (за вес) = 110р

ВАРИАНТ 2:
НО не будет ли верно считать процент доставки от цены с весом? 
Получается так: 
100р (за вес) + 20р (100р товар + 100р доставка за вес и с этого 10 процентов) = 120р 

Какой вариант будет логичнее?

**Comment by avdant** [comment]
Если мое мнение интересно, то я за первый вариант, так как все таки расчет доставки, каким бы он способом не считался, должен вестись от стоимости товаров.
Он логичнее и прозрачнее для покупателя.
Заказал товар к нему прибавилась стоимость по весу и стоимость по проценту.
А вообще, я что-то с трудом представляю ситуацию когда надо использовать это одновременно.
