### ISSUE TITLE
Добавить хэш в url для табов настроек

### ISSUE THREAD

**Issue by webinmd** [modx-pro/miniShop2#884]
### Резюме / Summary

В разделе miniShop2 :: Настройки добавить хэш или history api  для табов настроек. 

### Зачем это нужно / Why is it needed?

Удобно давать ссылки на конкретную вкладку в той же документации

**Comment by Ruslan-Aleev** [comment]
Эххх, эту тему я для MODX двигал годами, но мало что сделано было...

**Comment by webinmd** [comment]
> Эххх, эту тему я для MODX двигал годами, но мало что сделано было...

да, я видел issue для пагинации и фильтров #427
