### ISSUE TITLE
Изменить название параметра в методе addCss

### ISSUE THREAD

**Issue by Alekseevich-psk** [modx-pro/miniShop2#905]
## Сообщение об ошибке / Error message

`/**
    * @param string $script
    */
    public function addCss($script)
    {
        $script = $script . '?v=' . $this->miniShop2->version;
        parent::addCss($script);
    }`

[Смотреть сюда ](https://github.com/modx-pro/miniShop2/blob/687e2da482497f0aacbfe5e00d64747da69eb21f/core/components/minishop2/controllers/manager.class.php#L31)
### Environment

Версия minishop2-3.0.7

**Comment by webinmd** [comment]
это осталось наследство от родительского метода. 
Тут либо и в самом MODX изменять либо оставить
[Ссылка на метод](https://github.com/modxcms/revolution/blob/73bfd2712427f46d9f32730b86f335fbe3296703/core/src/Revolution/modManagerController.php#L846)
