### ISSUE TITLE
Checkout breaks when enabling emails to user and manager

### ISSUE THREAD

**Issue by lottaar** [modx-pro/miniShop2#93]
When "Email User" and "Email Manager" are enabled for a new order (Settings > Statuses > New), and the chunks set to the default tpl.msEmail.new.user and tpl.msEmail.new.manager, the checkout stops working. When clicking Submit on the checkout page nothing happens the first time. Clicking Submit again sends an empty order and the emails are sent to user and manager.

**Comment by bezumkin** [comment]
Try to disable php-apc

**Comment by lottaar** [comment]
Thanks for quick response! How do I disable php-apc?

**Comment by lottaar** [comment]
After some digging I found out that APC is something to do with cache, so I checked my Preferences on MAMP, and see that Cache is set to XCache, not APC. So does that mean the issue isn't to do with php-apc?

Oh, and another cache issue, probably unrelated but you never know. The product resources don't have an option to clear cache on save, like other resources do. So after editing a product I have to manually clear cache (Website > Clear cache). Is there a setting to enable clearing the cache on save somewhere?

**Comment by lottaar** [comment]
Hi Vasily,

I've done some more troubleshooting, and come to the conclusion that if I remove the first line, [[!msGetOrder?id=`[[+id]]`]], from the email chunks, the order and email go through ok. Unfortunately the only values that come through in the emails is the order ID and the order totals. [[+goods]], [[+cart_count]], [[+cart_weight]] don't return any results.

Do you have any other ideas what I could do?

Edit: This site is now also uploaded to a host who have confirmed that php_apc is NOT activated on their servers.

**Comment by bezumkin** [comment]
Can`t confirm that bug.

Do you have any news?

**Comment by Ibochkarev** [comment]
The bug does not play
